
/*

-- 생성자 :	이동호
-- 등록일 :	2024.10.28
-- 수정자 : -
-- 설 명  : 운영서버 데이터 > 개발서버에 데이터 동기화
-- 실행문 : 

*/
CREATE PROCEDURE [dbo].[DB_TABLE_SYNC_PUT]
( 
	@P_TABLE_NAME			NVARCHAR(100) = '',	
	@P_MODE					NVARCHAR(15) = ''	
	
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	DECLARE @RETURN_CODE INT = 0									-- 리턴코드(저장완료)
	DECLARE @RETURN_MESSAGE NVARCHAR(MAX) = DBO.GET_ERR_MSG('0')	-- 리턴메시지
	
	
	BEGIN TRAN
	BEGIN TRY 					
						
		IF @P_TABLE_NAME <> '' AND @P_MODE = 'INSERT'
		BEGIN


			DECLARE @SQL NVARCHAR(MAX)

			SET @SQL = N'TRUNCATE TABLE ' + @P_TABLE_NAME + ';
		
			INSERT INTO UMAC_ERP.DBO.'+ @P_TABLE_NAME +' SELECT * FROM REAL_UMAC_ERP.UMAC_ERP.DBO.'+ @P_TABLE_NAME +' WITH(NOLOCK)

			'
			EXEC SP_EXECUTESQL @SQL

		END

	COMMIT;

	END TRY
	
	BEGIN CATCH		

		IF @@TRANCOUNT > 0
		BEGIN 
			ROLLBACK TRAN

			
		SET @RETURN_CODE = -1
		SET @RETURN_MESSAGE = ERROR_MESSAGE()
		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()		-- 프로시저명
			, ERROR_MESSAGE()			-- 에러메시지
			, ERROR_LINE()				-- 에러라인
			, GETDATE()	
		END

	END CATCH

	SELECT @RETURN_CODE AS RETURN_CODE, @RETURN_MESSAGE AS RETURN_MESSAGE
END

GO

