
/*

-- 생성자 :	이동호
-- 등록일 :	2024.07.05
-- 수정자 : 
-- 수정일 : 
-- 설 명  : 입금내역 등록
-- 실행문 : 

DECLARE @P_JSONDT VARCHAR(8000) = '
[
	{"DEPOSIT_DT":"20240604", "VEN_CODE":"UM20070", "DEPOSIT_GB":"01", "DEPOSIT_AMT":"1000"},
	{"DEPOSIT_DT":"20240604", "VEN_CODE":"UM20071", "DEPOSIT_GB":"01", "DEPOSIT_AMT":"2000"},
	{"DEPOSIT_DT":"20240604", "VEN_CODE":"UM20072", "DEPOSIT_GB":"01", "DEPOSIT_AMT":"1000"}
]
'
EXEC PR_ACCT_DEPOSIT_MANUAL_HDR_PUT @P_JSONDT
--
*/
CREATE PROCEDURE [dbo].[PR_ACCT_DEPOSIT_MANUAL_HDR_PUT]
( 
	
	@P_JSONDT			VARCHAR(MAX) = '',
	@P_EMP_ID			VARCHAR(20) = ''
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	DECLARE @RETURN_CODE INT = 0									-- 리턴코드(저장완료)
	DECLARE @RETURN_MESSAGE NVARCHAR(MAX) = DBO.GET_ERR_MSG('0')	-- 리턴메시지

	BEGIN TRAN
	BEGIN TRY 	
		
		EXEC PR_ACCT_DEPOSIT_MANUAL_PUT @P_JSONDT, @P_EMP_ID, @RETURN_CODE OUT, @RETURN_MESSAGE OUT

		SELECT @RETURN_CODE AS RETURN_CODE, @RETURN_MESSAGE AS RETURN_MESSAGE 

		COMMIT;

	END TRY
	BEGIN CATCH	
				
		IF @@TRANCOUNT > 0
		BEGIN 
					
			ROLLBACK TRAN	
			
			SET @RETURN_CODE = -1
			SET @RETURN_MESSAGE = ERROR_MESSAGE()
			
			--에러 로그 테이블 저장
			INSERT INTO TBL_ERROR_LOG 
			SELECT ERROR_PROCEDURE()			-- 프로시저명
					, ERROR_MESSAGE()			-- 에러메시지
					, ERROR_LINE()				-- 에러라인
					, GETDATE()					
		END 

		SELECT @RETURN_CODE AS RETURN_CODE, @RETURN_MESSAGE AS RETURN_MESSAGE

	END CATCH
		
END

GO

