/*
-- 생성자 :	강세미
-- 등록일 :	2023.02.02
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 운송비관리 리스트
-- 실행문 : 
EXEC PR_DELIVERY_PRICE_LIST '',''
*/
CREATE PROCEDURE [dbo].[PR_DELIVERY_PRICE_LIST]
( 
	@P_TRANS_GB				NVARCHAR(1) = '',   -- 운송구분
	@P_TRANS_SECTION		NVARCHAR(6) = ''	  -- 운송구간
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	BEGIN TRY 
		SELECT ROW_NUMBER() OVER(ORDER BY TRANS_SECTION) AS ROW_NUM,
				 A.SEQ,
				 A.TRANS_GB,
				 B.CD_NM AS TRANS_GB_NM,
				 ISNULL(A.TRANS_SECTION,0) AS TRANS_SECTION,
				 ISNULL(A.TRANS_COST_1,0) AS TRANS_COST_1,
				 ISNULL(A.TRANS_COST_2,0) AS TRANS_COST_2,
				 ISNULL(A.TRANS_COST_3,0) AS TRANS_COST_3,
				 ISNULL(A.TRANS_COST_4,0) AS TRANS_COST_4,
				 ISNULL(A.TRANS_COST_5,0) AS TRANS_COST_5,
				 ISNULL(A.RENT_COST_1,0) AS RENT_COST_1,
				 ISNULL(A.RENT_COST_2,0) AS RENT_COST_2,
				 ISNULL(A.RENT_COST_3,0) AS RENT_COST_3,
				 ISNULL(A.RENT_COST_4,0) AS RENT_COST_4,
				 ISNULL(A.RENT_COST_5,0) AS RENT_COST_5
				 FROM CD_DELIVERY_PRICE AS A
		 INNER JOIN TBL_COMM_CD_MST AS B
					ON B.CD_CL = 'TRANS_GB' AND B.CD_ID = A.TRANS_GB
		 WHERE A.TRANS_GB = (CASE WHEN @P_TRANS_GB <> '' THEN @P_TRANS_GB ELSE A.TRANS_GB END)
		   AND A.TRANS_SECTION = (CASE WHEN @P_TRANS_SECTION <> '' THEN @P_TRANS_SECTION ELSE A.TRANS_SECTION END)
	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
	
END

GO

