/*
-- 생성자	:	최수민
-- 등록일	:	2023.10.08
-- 설 명	:	더존 광리항목 저장
-- 실행문 : EXEC PR_DOUZONE_MGMT_ITEM_PUT ''
*/
CREATE PROCEDURE [dbo].[PR_DOUZONE_MGMT_ITEM_PUT]
(
	@P_SCAN_CODE			NVARCHAR(14) = '',		-- 스캔코드
	@P_MGMT_ENTRY_1			NVARCHAR(4) = '',		-- 더존 저장품 구분
	@P_MGMT_ENTRY_2			NVARCHAR(4) = '',		-- 더존 원재료 구분
	@P_MGMT_ENTRY_3			NVARCHAR(4) = ''		-- 더존 제품매출 구분
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	DECLARE @RETURN_CODE INT = 0								-- 리턴코드
	DECLARE @RETURN_MESSAGE NVARCHAR(20) = '저장되었습니다.'	-- 리턴메시지

	BEGIN TRY 
		
						
		DECLARE @R_COUNT INT;
		SELECT @R_COUNT = COUNT(1) FROM TBL_DOUZONE_MGMT_ITEM WHERE SCAN_CODE = @P_SCAN_CODE;

		IF @R_COUNT > 0
		BEGIN 
			UPDATE TBL_DOUZONE_MGMT_ITEM
			SET 
				MGMT_ENTRY_1 = @P_MGMT_ENTRY_1,
				MGMT_ENTRY_2 = @P_MGMT_ENTRY_2,
				MGMT_ENTRY_3 = @P_MGMT_ENTRY_3
			WHERE SCAN_CODE = @P_SCAN_CODE;
		END
		ELSE
		BEGIN
			INSERT INTO TBL_DOUZONE_MGMT_ITEM
			(	
				SCAN_CODE,
				MGMT_ENTRY_1, 
				MGMT_ENTRY_2, 
				MGMT_ENTRY_3
			)
			VALUES
			(
				@P_SCAN_CODE,
				@P_MGMT_ENTRY_1,
				@P_MGMT_ENTRY_2,
				@P_MGMT_ENTRY_3
			);
		END

	END TRY
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	

		SET @RETURN_CODE = -1 -- 저장 실패
		SET @RETURN_MESSAGE = DBO.GET_ERR_MSG('-1')
	END CATCH
	
	
	SELECT @RETURN_CODE AS RETURN_CODE, @RETURN_MESSAGE AS RETURN_MESSAGE
END

GO

