/*
-- 생성자 :	강세미
-- 등록일 :	2024.09.06
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 한달 지난 로그데이터 삭제
-- 실행문 : 
*/
CREATE PROCEDURE [dbo].[PR_ERROR_LOG_DEL]
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
 	
	DECLARE @RETURN_CODE INT = 0			-- 리턴코드
	DECLARE @RETURN_MESSAGE NVARCHAR(30) = '저장되었습니다.'		-- 리턴메시지

	BEGIN TRAN
	BEGIN TRY
		
		DELETE 
		  FROM TBL_BATCH_LOG
		 WHERE END_TIME < DATEADD(MONTH, -1, GETDATE());

		DELETE 
		  FROM TBL_ERROR_LOG
		 WHERE IDATE < DATEADD(MONTH, -1, GETDATE());
		 
		DELETE 
		  FROM TBL_ERROR_LOG_APP
		 WHERE IDATE < DATEADD(MONTH, -1, GETDATE());

		DELETE 
		  FROM TBL_ERROR_LOG_WEB
		 WHERE IDATE < DATEADD(MONTH, -1, GETDATE());

		COMMIT;
	END TRY
	
	BEGIN CATCH		
		IF @@TRANCOUNT > 0
		BEGIN 
			ROLLBACK TRAN

			SET @RETURN_CODE = -1
			SET @RETURN_MESSAGE = ERROR_MESSAGE()

			--에러 로그 테이블 저장
			INSERT INTO TBL_ERROR_LOG 
			SELECT ERROR_PROCEDURE()		-- 프로시저명
				, ERROR_MESSAGE()			-- 에러메시지
				, ERROR_LINE()				-- 에러라인
				, GETDATE()	
		END 
	END CATCH

	SELECT @RETURN_CODE AS RETURN_CODE, @RETURN_MESSAGE AS RETURN_MESSAGE
END

GO

