
/*
-- 생성자 :	최수민
-- 등록일 :	2024.11.07
-- 설 명  :	모바일 주문서 목록
-- 수정자 : 
-- 실행문 : 

EXEC PR_MO_ORDER_REGISTER_LIST ''

*/
CREATE PROCEDURE [dbo].[PR_MO_ORDER_REGISTER_LIST]
( 	
	@P_USER_ID			NVARCHAR(20) = ''	-- 사용자ID
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	BEGIN TRY 

		DECLARE @P_FROM_ORD_DT		NVARCHAR(8)	= '',	-- 조회 시작일
				@P_TO_ORD_DT		NVARCHAR(8)	= ''	-- 조회 종료일
				;

		SET @P_FROM_ORD_DT = FORMAT(DATEADD(DAY, -14, GETDATE()), 'yyyyMMdd'); --당일 기준 -14일
		SET @P_TO_ORD_DT = FORMAT(DATEADD(DAY, 7, GETDATE()), 'yyyyMMdd'); --당일기준 +7

		SELECT HDR.ORD_NO
			 , HDR.VEN_CODE
			 , PTN.VEN_NAME
			 , HDR.DELIVERY_REQ_DT
			 , HDR.DELIVERY_CODE
			 , ISNULL(E.DELIVERY_NAME, '기본') AS DELIVERY_NAME
			 , HDR.ORD_STAT
			 , F.CD_NM AS ORD_STAT_NM
		  FROM PO_ORDER_HDR AS HDR
		  LEFT OUTER JOIN CD_PARTNER_MST AS PTN ON HDR.VEN_CODE = PTN.VEN_CODE
		  LEFT OUTER JOIN TBL_COMM_CD_MST AS F ON F.CD_CL = 'ORD_STAT' AND HDR.ORD_STAT = F.CD_ID
		  LEFT OUTER JOIN CD_PARTNER_DELIVERY AS E ON HDR.VEN_CODE = E.VEN_CODE AND HDR.DELIVERY_CODE = E.DELIVERY_CODE
		 WHERE HDR.DELIVERY_REQ_DT BETWEEN @P_FROM_ORD_DT AND @P_TO_ORD_DT
		   --AND PTN.MGNT_USER_ID = @P_USER_ID
		  -- AND HDR.IEMP_ID = @P_USER_ID
		 ORDER BY HDR.DELIVERY_REQ_DT
	
	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
	
END

GO

