/*
-- 생성자 :	윤현빈
-- 등록일 :	2024.11.29
-- 수정일 : - 
-- 설 명  : 주문등록 DTL 조회 (리포트)
-- 실행문 : 
*/
CREATE PROCEDURE [dbo].[PR_ORDER_DTL_REPORT_LIST]
( 
	@P_ORD_NO	NVARCHAR(11) = '',   -- 주문번호
	@P_ORD_STAT NVARCHAR(2) = ''		-- 주문상태
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
 
	BEGIN TRY 
		SELECT ROW_NUMBER() OVER(ORDER BY A.SEQ) AS ROW_NUM,
				A.SCAN_CODE,
				A.ORD_QTY,
				CASE WHEN @P_ORD_STAT IN ('10', '25') THEN A.ORD_QTY ELSE ISNULL(A.PICKING_QTY,0) END AS PICKING_QTY,
				CASE WHEN @P_ORD_STAT IN ('10', '25') THEN A.ORD_SPRC ELSE ISNULL(A.PICKING_SPRC,0) END AS PICKING_SPRC,
				CASE WHEN @P_ORD_STAT IN ('10', '25') THEN A.ORD_SVAT ELSE ISNULL(A.PICKING_SVAT,0) END AS PICKING_SVAT,
				CASE WHEN @P_ORD_STAT IN ('10', '25') THEN A.ORD_SAMT ELSE ISNULL(A.PICKING_SAMT,0) END AS PICKING_SAMT,
				A.ORD_NO,
				B.ITM_NAME,
				CASE WHEN SEQ <> 0 THEN B.ITM_NAME_DETAIL ELSE CONCAT('(샘플)', B.ITM_NAME_DETAIL) END AS ITM_NAME_DETAIL,
				B.UNIT_CAPACITY,
				B.WEIGHT_GB,
				B.TAX_GB,
				0 AS SEQ,
				'' AS ITM_GB,
				'' AS ITM_GB_NM,
				0 AS IPSU_QTY,
				0.0 AS ORD_SPRC,
				0.0 AS ORD_SVAT,
				0.0 AS ORD_SAMT,
				0.0 AS ORD_SALE,
				'' AS TAX_GB_NM,
				'' AS DOCUMENT_REQ,
				'' AS DOCUMENT_REQ_NM,
				'' AS PICKING_EMP_NO,
				GETDATE() AS PICKING_SDATE,
				GETDATE() AS PICKING_EDATE,
				'' AS REMARKS,
				'' AS UNIT_NM,
				0.0 AS CUR_INV_QTY,
				0.0 AS AVL_INV_QTY
			FROM VIEW_ORDER_DTL_SAMPLE_SUM AS A
			INNER JOIN CD_PRODUCT_CMN AS B ON A.SCAN_CODE = B.SCAN_CODE
			WHERE ORD_NO = @P_ORD_NO

	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
	
END

GO

