/*
-- 생성자 :	강세미
-- 등록일 :	2024.06.04
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 거래처매출조회
-- 실행문 : EXEC PR_PARTNER_SALES_LIST '','20240401','20240603',''
*/
CREATE PROCEDURE [dbo].[PR_PARTNER_SALES_LIST]
	@P_VEN_CODE			VARCHAR(7),	-- 거래처코드
	@P_FROM_SALE_DT		VARCHAR(8),	-- 조회시작일자
	@P_TO_SALE_DT		VARCHAR(8),	-- 조회종료일자
	@P_PARTNER_GB		VARCHAR(2)	-- LOT거래처 구분
	--@P_VEN_GB			VARCHAR(2)	-- 거래처 구분
AS 
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	BEGIN TRY 

		SELECT A.VEN_CODE,
			   SUM(A.ORD_CNT) AS ORD_CNT,
			   SUM(A.SALE_TOTAL_AMT) AS SALE_TOTAL_AMT,
			   B.VEN_NAME
		FROM SL_SALE_VEN AS A
			INNER JOIN CD_PARTNER_MST AS B ON A.VEN_CODE = B.VEN_CODE
		WHERE A.SALE_DT BETWEEN @P_FROM_SALE_DT AND @P_TO_SALE_DT
			AND 1 = (CASE WHEN @P_VEN_CODE = '' THEN 1 WHEN @P_VEN_CODE != '' AND A.VEN_CODE = @P_VEN_CODE THEN 1 ELSE 0 END)
			--AND 1 = (CASE WHEN @P_VEN_GB = '' THEN 1 WHEN @P_VEN_GB != '' AND B.VEN_GB = @P_VEN_GB THEN 1 ELSE 0 END)
		GROUP BY A.VEN_CODE, B.VEN_NAME

	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
	
END

GO

