/*
-- 생성자 :	윤현빈
-- 등록일 :	2024.06.12
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 여신한도 저장
-- 실행문 : EXEC PR_PARTNER_CREDIT_LIMIT_PUT '','','',''
*/
CREATE PROCEDURE [dbo].[PR_PARTNER_CREDIT_LIMIT_PUT]
	@P_VEN_CODE			NVARCHAR(7),	-- 거래처코드
	@CREDIT_LIMIT_YN	NVARCHAR(1), 	-- 한도설정
	@CREDIT_LIMIT		NUMERIC(13,0), 	-- 한도금액
	@P_EMP_ID			NVARCHAR(20)	-- 아이디
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
	DECLARE @RETURN_CODE INT = 0				-- 리턴코드
	DECLARE @RETURN_MESSAGE NVARCHAR(20) = ''	-- 리턴메시지

	BEGIN TRAN
	BEGIN TRY

		UPDATE CD_PARTNER_MST
			SET CREDIT_LIMIT_YN = @CREDIT_LIMIT_YN
			  , CREDIT_LIMIT = @CREDIT_LIMIT
			  , UDATE = GETDATE()
			  , UEMP_ID = @P_EMP_ID
		   WHERE VEN_CODE = @P_VEN_CODE
		;
		
		SET @RETURN_CODE = 0; -- 저장완료
		SET @RETURN_MESSAGE = DBO.GET_ERR_MSG('0');
		COMMIT;

	END TRY
	
	BEGIN CATCH		
		IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRAN
			
			--에러 로그 테이블 저장
			INSERT INTO TBL_ERROR_LOG 
			SELECT ERROR_PROCEDURE()	-- 프로시저명
			, ERROR_MESSAGE()			-- 에러메시지
			, ERROR_LINE()				-- 에러라인
			, GETDATE();
		
			SET @RETURN_CODE = -1; -- 저장 실패
			SET @RETURN_MESSAGE = DBO.GET_ERR_MSG('-1');
			
			SELECT @RETURN_CODE AS RETURN_CODE, @RETURN_MESSAGE AS RETURN_MESSAGE
		END
			
	END CATCH

	SELECT @RETURN_CODE AS RETURN_CODE, @RETURN_MESSAGE AS RETURN_MESSAGE

END

GO

