/*
-- 생성자 :	윤현빈
-- 등록일 :	2024.07.04
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 재고조사 일정 삭제
-- 실행문 : EXEC PR_STOCK_SCHD_DEL '20240701'
*/
CREATE PROCEDURE [dbo].[PR_STOCK_SCHD_DEL]
( 
	@P_SURVEY_ID	NVARCHAR(8) = ''	-- 재고조사 ID
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	DECLARE @RETURN_CODE 	INT 			= 0		-- 리턴코드
	DECLARE @RETURN_MESSAGE NVARCHAR(10) 	= '' 	-- 리턴메시지

	BEGIN TRAN
	BEGIN TRY

		IF NOT EXISTS (
			SELECT 1
				FROM IV_SCHEDULER AS A
				INNER JOIN IV_STOCK_SURVEY AS B ON A.SURVEY_ID = B.SURVEY_ID
			   WHERE A.SURVEY_ID = @P_SURVEY_ID
		)
		BEGIN
			DELETE FROM IV_SCHEDULER WHERE SURVEY_ID = @P_SURVEY_ID;
			
			SET @RETURN_CODE = 93; -- 삭제완료
			SET @RETURN_MESSAGE = DBO.GET_ERR_MSG('93');

		END
		ELSE
		BEGIN
			SET @RETURN_CODE = -1; -- 삭제완료
			SET @RETURN_MESSAGE = DBO.GET_ERR_MSG('-1');
		END
		
		COMMIT;
	
	END TRY
	
	BEGIN CATCH		
		IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRAN

			--에러 로그 테이블 저장
			INSERT INTO TBL_ERROR_LOG 
			SELECT ERROR_PROCEDURE()	-- 프로시저명
			, ERROR_MESSAGE()			-- 에러메시지
			, ERROR_LINE()				-- 에러라인
			, GETDATE();
		
			SET @RETURN_CODE = -1; -- 저장 실패
			SET @RETURN_MESSAGE = DBO.GET_ERR_MSG('-1');
			
			SELECT @RETURN_CODE AS RETURN_CODE, @RETURN_MESSAGE AS RETURN_MESSAGE
		END
			
	END CATCH

	SELECT @RETURN_CODE AS RETURN_CODE, @RETURN_MESSAGE AS RETURN_MESSAGE

END

GO

