/*
-- 생성자 :	윤현빈
-- 등록일 :	2024.08.13
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : SET 작업 조회, 자재 투입 현황(BOM)
-- 실행문 : EXEC PR_SET_PROD_COMP_REGISTER_LIST '','',''
*/
CREATE PROCEDURE [dbo].[PR_SET_PROD_COMP_REGISTER_LIST]
( 
	@P_SET_PLAN_ID			NVARCHAR(11) = '',		-- 작업코드
	@P_SET_PROD_SDATE		NVARCHAR(8) = '',		-- 생산시작일자
	@P_SET_PROD_EDATE		NVARCHAR(8) = ''		-- 생산종료일자
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	BEGIN TRY 	
		SELECT A.PROD_DT
			 , A.SET_COMP_CD AS SCAN_CODE
			 , MST_PRD.ITM_NAME_DETAIL AS ITM_NAME
			 , ISNULL(A.LOT_NO, '') AS LOT_NO
			 , A.COMP_QTY
			 , MST_USR.USER_NM
			FROM PD_SET_RESULT_COMP AS A
			INNER JOIN CD_PRODUCT_CMN AS MST_PRD ON A.SET_COMP_CD = MST_PRD.SCAN_CODE
			INNER JOIN TBL_USER_MST AS MST_USR ON A.IEMP_ID = MST_USR.USER_ID
		   WHERE A.PROD_DT BETWEEN @P_SET_PROD_SDATE AND @P_SET_PROD_EDATE
		     AND A.SET_PLAN_ID = @P_SET_PLAN_ID
			 AND A.RESTORE_YN = 'N'
			 AND A.COMP_QTY != 0
		   ORDER BY A.PROD_DT DESC, A.SCAN_CODE


		   -- 2024-08-22 아래 쿼리로 SUM 하려 했으나 등록자가 달라질 수 있어서 SUM 하지 않은 코드 사용
		--SELECT A.*
		--	 , MST_PRD.ITM_NAME
		--	 , MST_USR.USER_NM
		--	FROM (
		--		SELECT A.PROD_DT
		--			 , A.SET_COMP_CD AS SCAN_CODE
		--			 , ISNULL(A.LOT_NO, '') AS LOT_NO
		--			 , SUM(A.COMP_QTY) AS COMP_QTY
		--			FROM PD_SET_RESULT_COMP AS A
		--		   WHERE A.PROD_DT BETWEEN @P_SET_PROD_SDATE AND @P_SET_PROD_EDATE
		--			 AND A.SET_PLAN_ID = @P_SET_PLAN_ID
		--			 AND A.RESTORE_YN = 'N'
		--			 AND A.COMP_QTY != 0
		--		   GROUP BY A.PROD_DT, A.SET_COMP_CD, ISNULL(A.LOT_NO, '')
		--	) AS A
		--	INNER JOIN CD_PRODUCT_CMN AS MST_PRD ON A.SCAN_CODE = MST_PRD.SCAN_CODE
		--	INNER JOIN TBL_USER_MST AS MST_USR ON A.IEMP_ID = MST_USR.USER_ID
		--   ORDER BY A.PROD_DT DESC, A.SCAN_CODE

	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
END

GO

