/*
-- 생성자 :	강세미
-- 등록일 :	2024.06.17
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 매출입내역수정 > 상세 조회
-- 실행문 : EXEC PR_SALES_DETAIL_LIST '2240725001'
*/
CREATE PROCEDURE [dbo].[PR_SALES_DETAIL_LIST]
	@P_ORD_NO			VARCHAR(11)		-- 주문번호
AS 
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	BEGIN TRY 
		DECLARE @IO_GB NVARCHAR(1)
		SET @IO_GB = LEFT(@P_ORD_NO, 1);

		IF @IO_GB = '2'
		BEGIN 
			WITH TEMP AS (
			SELECT A.ORD_NO,
					A.SCAN_CODE,
					A.ORD_QTY AS ORD_QTY,
					ISNULL((CASE WHEN B.WEIGHT_GB = 'QTY' THEN C.PICKING_QTY ELSE A.PICKING_QTY END), 0) AS QTY,
					ISNULL((CASE WHEN B.WEIGHT_GB = 'QTY' THEN C.PICKING_QTY ELSE A.PICKING_QTY END), 0) AS BEFO_QTY,
					ISNULL(A.PICKING_SPRC,0) AS SALE_PRC,
					ISNULL(A.PICKING_SVAT,0) AS SALE_VAT,
					ISNULL((A.PICKING_SPRC + A.PICKING_SVAT),0) AS SALE_AMT,
					ISNULL(A.PICKING_SAMT,0) AS TOTAL_AMT,
					--ISNULL(((A.PICKING_SPRC + A.PICKING_SVAT) * (CASE WHEN B.WEIGHT_GB = 'QTY' THEN C.PICKING_QTY ELSE A.PICKING_QTY END)),0) AS TOTAL_AMT,
					A.REMARKS_SALES,
					B.ITM_NAME,
					B.WEIGHT_GB,
					B.TAX_GB,
					C.LOT_NO,
					'D' AS GUBUN
			FROM PO_ORDER_DTL AS A
				INNER JOIN CD_PRODUCT_CMN AS B ON A.SCAN_CODE = B.SCAN_CODE
				LEFT OUTER JOIN PO_ORDER_LOT AS C
					ON A.ORD_NO = C.ORD_NO AND A.SCAN_CODE = C.SCAN_CODE
			UNION ALL 
			SELECT A.ORD_NO,
					CONCAT('(샘플)', A.SCAN_CODE) AS SCAN_CODE,
					A.ORD_QTY AS ORD_QTY,
					A.PICKING_QTY AS QTY,
					A.PICKING_QTY AS BEFO_QTY,
					'0' AS SALE_PRC,
					'0' AS SALE_VAT,
					'0' AS SALE_AMT,
					'0' AS TOTAL_AMT,
					A.REMARKS_SALES,
					CONCAT('(샘플)',B.ITM_NAME) AS ITM_NAME,
					B.WEIGHT_GB,
					B.TAX_GB,
					C.LOT_NO,
					'S' AS GUBUN
			FROM PO_ORDER_SAMPLE AS A
				INNER JOIN CD_PRODUCT_CMN AS B ON A.SCAN_CODE = B.SCAN_CODE
				LEFT OUTER JOIN ( SELECT ORD_NO, SCAN_CODE, MIN(LOT_NO) AS LOT_NO
									FROM PO_ORDER_LOT
									GROUP BY ORD_NO, SCAN_CODE
				) AS C ON A.ORD_NO = C.ORD_NO AND A.SCAN_CODE = C.SCAN_CODE
			) 
			SELECT A.ORD_NO,
				A.SCAN_CODE,
				ORD_QTY,
				(CASE WHEN A.GUBUN = 'D' AND B.QTY IS NOT NULL THEN A.QTY - B.QTY ELSE A.QTY END) AS QTY,
				(CASE WHEN A.GUBUN = 'D' AND B.QTY IS NOT NULL THEN A.QTY - B.QTY ELSE A.QTY END) AS BEFO_QTY,
				--QTY,
				SALE_PRC,
				SALE_VAT,
				SALE_AMT,
				--TOTAL_AMT,
				ISNULL(((SALE_PRC + SALE_VAT) * (CASE WHEN A.GUBUN = 'D' AND B.QTY IS NOT NULL THEN A.QTY - B.QTY ELSE A.QTY END)),0) AS TOTAL_AMT,
				REMARKS_SALES,
				ITM_NAME,
				WEIGHT_GB,
				TAX_GB,
				A.LOT_NO,
				GUBUN
			FROM TEMP AS A
			LEFT OUTER JOIN (
				SELECT 
					ORD_NO, REPLACE(SCAN_CODE, '(샘플)', '') AS SCAN_CODE, LOT_NO, QTY
				FROM TEMP WHERE GUBUN = 'S'
			) AS B ON A.ORD_NO = B.ORD_NO AND A.SCAN_CODE = B.SCAN_CODE AND A.LOT_NO = B.LOT_NO
			WHERE 1= ( CASE WHEN @IO_GB = 1 THEN 2 ELSE 1 END) 
				  AND A.ORD_NO = @P_ORD_NO
		END
		ELSE
		BEGIN
			SELECT A.ORD_NO,
				   A.SCAN_CODE,
				   A.ORD_QTY AS ORD_QTY,
				   A.PUR_QTY AS QTY,
				   A.PUR_QTY AS BEFO_QTY,
				   A.PUR_WPRC AS SALE_PRC,
				   A.PUR_WVAT AS SALE_VAT,
				   (A.PUR_WPRC + A.PUR_WVAT) AS SALE_AMT,
				   A.PUR_WAMT AS TOTAL_AMT,
				   A.REMARKS_SALES,
				   B.ITM_NAME,
				   B.WEIGHT_GB,
				   B.TAX_GB,
				   '' AS LOT_NO,
				   '' AS GUBUN
			FROM PO_PURCHASE_DTL AS A
				INNER JOIN CD_PRODUCT_CMN AS B ON A.SCAN_CODE = B.SCAN_CODE
			WHERE 1= ( CASE WHEN @IO_GB = 2 THEN 2 ELSE 1 END)	
				AND A.ORD_NO = @P_ORD_NO
		END 
	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
	
END

GO

