/*
-- 생성자 :	윤현빈
-- 등록일 :	2024.08.09
-- 수정자 : 2024.11.20 강세미 - 소비기한 추가
-- 수정일 : - 
-- 설 명  : SET 생산 일정 조회
-- 실행문 : EXEC PR_SET_PLAN_LIST '','','','',''
*/
CREATE PROCEDURE [dbo].[PR_SET_PLAN_LIST]
( 
	@P_SET_PLAN_SDATE		NVARCHAR(8) ,			-- 작업예정시작일
	@P_SET_PLAN_EDATE		NVARCHAR(8) = '',		-- 작업예정종료일
	@P_SET_PLAN_ID_NM		NVARCHAR(100) = ''		-- 작업명
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	BEGIN TRY 	
		SELECT ROW_NUMBER() OVER(ORDER BY A.SET_STATUS, A.SET_PLAN_ID DESC) AS ROW_NUM
		     , A.SET_PLAN_ID
			 , A.SET_PLAN_NM
			 , A.SET_PLAN_SDATE
			 , A.SET_PLAN_EDATE
			 , A.SET_STATUS
			 , B.CD_NM AS SET_STATUS_NM
			 , C.USER_NM AS IEMP_ID
			 , CONVERT(VARCHAR(8), A.IDATE, 112) AS IDATE
			FROM PD_SET_PLAN_MST AS A
			INNER JOIN TBL_COMM_CD_MST AS B ON A.SET_STATUS = B.CD_ID AND B.CD_CL = 'SET_STATUS'
			INNER JOIN TBL_USER_MST AS C ON A.IEMP_ID = C.USER_ID
		   WHERE (A.SET_PLAN_SDATE <= @P_SET_PLAN_EDATE AND A.SET_PLAN_EDATE >= @P_SET_PLAN_SDATE)
		     AND (A.SET_PLAN_ID LIKE '%'+@P_SET_PLAN_ID_NM+'%' OR A.SET_PLAN_NM LIKE '%'+@P_SET_PLAN_ID_NM+'%')
	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
END

GO

