/*
-- 생성자 :	윤현빈
-- 등록일 :	2024.08.09
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : SET 생산 계획 조회
-- 실행문 : EXEC PR_SET_PLAN_HDR_LIST '','','','',''
*/
CREATE PROCEDURE [dbo].[PR_SET_PLAN_PROD_LIST]
( 
	@P_SET_PLAN_ID			NVARCHAR(11) = ''		-- 작업명
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	BEGIN TRY 	

		SELECT ROW_NUMBER() OVER(ORDER BY A.SCAN_CODE) AS ROW_NUM
		     , A.SCAN_CODE
			 , B.ITM_CODE
			 , B.ITM_NAME_DETAIL AS ITM_NAME
			 , CASE WHEN B.IPSU_QTY IS NOT NULL THEN A.PLAN_QTY / B.IPSU_QTY ELSE NULL END AS PLAN_BOX_QTY
			 , A.PLAN_QTY
			 , B.LOT_OIL_GB
			 , B.LOT_PARTNER_GB
			 , B.PLT_BOX_QTY
			 , B.IPSU_QTY
			 --, ISNULL(CONVERT(NVARCHAR(10), FORMAT(CAST(A.SET_EXPIRY_DATE AS DATE), 'yyyy-MM-dd'), 120), CONVERT(NVARCHAR(10), DATEADD(DAY, -1, DATEADD(YEAR, 2, GETDATE())), 120)) AS SET_EXPIRY_DATE  
			 , CONVERT(NVARCHAR(10), FORMAT(CAST(A.SET_EXPIRY_DATE AS DATE), 'yyyy-MM-dd'), 120) AS SET_EXPIRY_DATE  
			FROM PD_SET_PLAN_PROD AS A
			INNER JOIN CD_PRODUCT_CMN AS B ON A.SCAN_CODE = B.SCAN_CODE
		   WHERE A.SET_PLAN_ID = @P_SET_PLAN_ID
		   
	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
END

GO

