/*
-- 생성자 :	윤현빈
-- 등록일 :	2024.08.13
-- 수정자 : 2024.11.20 강세미 - 확정구분 추가
-- 수정일 : - 
-- 설 명  : SET 작업 조회, 생산현황상세
-- 실행문 : EXEC PR_SET_PROD_REGISTER_LIST '','',''
*/
CREATE PROCEDURE [dbo].[PR_SET_PROD_REGISTER_LIST]
( 
	@P_SET_PLAN_ID			NVARCHAR(11) = '',		-- 작업코드
	@P_SET_PROD_SDATE		NVARCHAR(8) = '',		-- 생산시작일자
	@P_SET_PROD_EDATE		NVARCHAR(8) = ''		-- 생산종료일자
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	BEGIN TRY 	
	
		SELECT ROW_NUMBER() OVER(ORDER BY A.PROD_CFM_FLAG, A.PROD_DT, A.SCAN_CODE) AS ROW_NUM
		     , A.SET_PLAN_ID
			 , A.PROD_DT
			 , A.SCAN_CODE
			 , MST_PRD.ITM_NAME_DETAIL AS ITM_NAME
			 --, A.PROD_QTY AS PROD_QTY
			 , CASE WHEN MST_PRD.IPSU_QTY IS NOT NULL THEN A.PROD_QTY / MST_PRD.IPSU_QTY ELSE NULL END AS PROD_BOX_QTY
			 , A.PROD_QTY
			 , A.PROD_CFM_FLAG
			 , LOT_MST.LOT_NO
			 , MST_PRD.IPSU_QTY
			FROM PD_SET_RESULT_PROD AS A
			INNER JOIN CD_PRODUCT_CMN AS MST_PRD ON A.SCAN_CODE = MST_PRD.SCAN_CODE
			LEFT OUTER JOIN CD_LOT_MST AS LOT_MST ON A.PROD_DT = LOT_MST.PROD_DT AND A.SCAN_CODE = LOT_MST.SCAN_CODE
		   WHERE A.PROD_DT BETWEEN @P_SET_PROD_SDATE AND @P_SET_PROD_EDATE
		     AND A.SET_PLAN_ID = @P_SET_PLAN_ID
			 AND A.PROD_QTY != 0

	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
END

GO

