/*
-- 생성자 :	강세미
-- 등록일 :	2023.03.18
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 배차관리 헤더 조회
-- 실행문 : 
EXEC PR_TRANS_MANAGE_HDR_LIST '2240621005'
*/
CREATE PROCEDURE [dbo].[PR_TRANS_MANAGE_HDR_LIST]
( 
	@P_ORD_NO	NVARCHAR(11) = ''			  -- 주문번호
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
 	DECLARE @IO_GB INT = 0;		-- 입출고구분

	SET @IO_GB = CASE WHEN LEFT(@P_ORD_NO,1) = 1 THEN 1 ELSE 2 END

	BEGIN TRY
	EXEC UMAC_CERT_OPEN_KEY; -- OPEN
		IF @IO_GB = 1
			BEGIN
				SELECT A.ORD_NO,
					   A.ORD_DT,
					   A.DELIVERY_IN_DT AS DELIVERY_DT,
					   A.ORD_AMT,
					   A.VEN_CODE,
					   A.DELIVERY_CODE,
					   A.R_POST_NO,
					   A.R_ADDR,
					   ISNULL(A.R_ADDR_DTL,'') AS R_ADDR_DTL,
					   A.REMARKS,
					   '' AS DELIVERY_REQ_DT,
					   B.VEN_NAME,
					   C.CAR_GB,
					   C.TRANS_COST,
					   C.RENT_COST,
					   C.CAR_NO,
					   C.GROUP_NO,
					   --C.MOBIL_NO,
					   DBO.GET_DECRYPT(C.MOBIL_NO) AS MOBIL_NO,
					   C.ENTRANCE_TIME,
					   D.CD_NM AS CAR_GB_NM,
					   E.TRANS_SECTION,
					   --(CASE WHEN F.TRANS_SECTION IS NULL THEN (SELECT TRANS_SECTION FROM CD_DELIVERY_PRICE WHERE SEQ = A.DELIVERY_PRICE_SEQ) ELSE F.TRANS_SECTION END) AS TRANS_SECTION
					   F.DELIVERY_NAME,
					   F.DELIVERY_GB,
					   (CASE WHEN F.DELIVERY_GB = '2' THEN 
					   CONCAT(G.DELIVERY_NAME, '-', CHAR(13)+CHAR(10), F.DELIVERY_NAME) ELSE '' END) AS FULL_DELIVERY_NAME,
					   H.DRIVER_NAME
				  FROM PO_PURCHASE_HDR AS A
						 INNER JOIN CD_PARTNER_MST AS B
							ON B.VEN_CODE = A.VEN_CODE
						 LEFT OUTER JOIN PO_SCALE AS C
							ON C.ORD_NO = A.ORD_NO
						 LEFT OUTER JOIN TBL_COMM_CD_MST AS D
							ON D.CD_CL = 'CAR_GB' AND D.CD_ID = C.CAR_GB
						 LEFT OUTER JOIN CD_DELIVERY_PRICE AS E
							ON A.DELIVERY_PRICE_SEQ = E.SEQ
					     LEFT OUTER JOIN CD_PARTNER_DELIVERY AS F
							ON F.VEN_CODE = A.VEN_CODE AND F.DELIVERY_CODE = A.DELIVERY_CODE 
						LEFT OUTER JOIN CD_PARTNER_DELIVERY AS G
							ON G.VEN_CODE = F.VEN_CODE 
							AND LEFT(G.DELIVERY_CODE, 5) = LEFT(F.DELIVERY_CODE, 5)
							AND G.DELIVERY_GB = '1'
						LEFT OUTER JOIN PO_CAR_INFO AS H ON H.CAR_NO = C.CAR_NO
				 WHERE A.ORD_NO = @P_ORD_NO
			END
		ELSE 
			BEGIN
				SELECT A.ORD_NO,
						 A.ORD_DT,
						 A.DELIVERY_DEC_DT AS DELIVERY_DT,
						 A.ORD_AMT,
						 A.VEN_CODE,
						 A.DELIVERY_CODE,
						 A.R_POST_NO,
						 A.R_ADDR,
						 ISNULL(A.R_ADDR_DTL,'') AS R_ADDR_DTL,
						 A.REMARKS,
						 FORMAT(CAST(A.DELIVERY_REQ_DT AS DATETIME), 'yyyy-MM-dd') AS DELIVERY_REQ_DT,
						 B.VEN_NAME,
						 C.CAR_GB,
						 C.TRANS_COST,
						 C.RENT_COST,
						 C.CAR_NO,
					     C.GROUP_NO,
						 --C.MOBIL_NO,
					   	 DBO.GET_DECRYPT(C.MOBIL_NO) AS MOBIL_NO,
						 C.ENTRANCE_TIME,
						 D.CD_NM AS CAR_GB_NM,
						 E.TRANS_SECTION,
						 F.DELIVERY_NAME,
						 F.DELIVERY_GB,
					     (CASE WHEN F.DELIVERY_GB = '2' THEN 
					     CONCAT(G.DELIVERY_NAME, '-', CHAR(13)+CHAR(10) , F.DELIVERY_NAME) ELSE '' END) AS FULL_DELIVERY_NAME,
					     H.DRIVER_NAME
				  FROM PO_ORDER_HDR AS A
					    INNER JOIN CD_PARTNER_MST AS B
							ON B.VEN_CODE = A.VEN_CODE
					    LEFT OUTER JOIN PO_SCALE AS C
							ON C.ORD_NO = A.ORD_NO
					    LEFT OUTER JOIN TBL_COMM_CD_MST AS D
							ON D.CD_CL = 'CAR_GB' AND D.CD_ID = C.CAR_GB
						LEFT OUTER JOIN CD_DELIVERY_PRICE AS E
							ON A.DELIVERY_PRICE_SEQ = E.SEQ
					    LEFT OUTER JOIN CD_PARTNER_DELIVERY AS F
							ON F.VEN_CODE = A.VEN_CODE AND F.DELIVERY_CODE = A.DELIVERY_CODE
						LEFT OUTER JOIN CD_PARTNER_DELIVERY AS G
							ON G.VEN_CODE = F.VEN_CODE 
							AND LEFT(G.DELIVERY_CODE, 5) = LEFT(F.DELIVERY_CODE, 5)
							AND G.DELIVERY_GB = '1'
						LEFT OUTER JOIN PO_CAR_INFO AS H ON H.CAR_NO = C.CAR_NO
				 WHERE A.ORD_NO = @P_ORD_NO
			END
	EXEC UMAC_CERT_CLOSE_KEY -- CLOSE
	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
	
END

GO

