/*
-- 생성자 :	윤현빈
-- 등록일 :	2024.05.13
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 시험성적서 관리 LOT리스트 조회
-- 실행문 : EXEC PR_TEST_REPORT_DETAIL_LOT_LIST  '','',''
*/
CREATE PROCEDURE [dbo].[PR_TEST_REPORT_DETAIL_LOT_LIST]
	@P_SCAN_CODE		NVARCHAR(14),	-- 상품코드
	@P_FROM_PROD_DT		NVARCHAR(10),	-- from 생산일자
	@P_TO_PROD_DT		NVARCHAR(10)	-- to 생산일자
AS 
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	BEGIN TRY 
		--SELECT ROW_NUMBER() OVER(ORDER BY A.PROD_DT DESC) AS ROW_NUM
		--     , A.PROD_DT
		--	 , ISNULL(C.EXPIRATION_DT, '') AS EXPIRATION_DT
		--     , A.LOT_NO
		--     , B.USER_NM AS UEMP_NM
		--     , CONVERT(NVARCHAR(8), A.UDATE, 112) AS UDATE
		--	FROM PD_TEST_REPORT AS A
		--	INNER JOIN TBL_USER_MST AS B ON A.UEMP_ID = B.USER_ID
		--	LEFT OUTER JOIN CD_LOT_MST AS C ON A.PROD_DT = C.PROD_DT AND A.SCAN_CODE = C.SCAN_CODE AND A.LOT_NO = C.LOT_NO
		--   WHERE A.PROD_DT BETWEEN @P_FROM_PROD_DT AND @P_TO_PROD_DT
		--     AND A.SCAN_CODE = @P_SCAN_CODE
		
		SELECT ROW_NUMBER() OVER(ORDER BY A.PROD_DT DESC) AS ROW_NUM
		     , A.PROD_DT
			 , ISNULL(A.EXPIRATION_DT, '') AS EXPIRATION_DT
		     , A.LOT_NO
		     , B.USER_NM AS UEMP_NM
		     , CONVERT(NVARCHAR(8), C.UDATE, 112) AS UDATE
			FROM CD_LOT_MST AS A
			LEFT OUTER JOIN PD_TEST_REPORT AS C ON A.PROD_DT = C.PROD_DT AND A.SCAN_CODE = C.SCAN_CODE AND A.LOT_NO = C.LOT_NO
			LEFT OUTER JOIN TBL_USER_MST AS B ON C.UEMP_ID = B.USER_ID
		   WHERE A.PROD_DT BETWEEN @P_FROM_PROD_DT AND @P_TO_PROD_DT
		     AND A.SCAN_CODE = @P_SCAN_CODE

	END TRY
	BEGIN CATCH	
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH

END

GO

