/*
-- 생성자 :	강세미
-- 등록일 :	2024.05.09
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 배차상세내역조회
-- 실행문 : 
EXEC PR_TRANS_DETAIL_LIST_BY_GB '3','', '', '20240501', '20240508', '', '', '', '', '123배9409'
*/
CREATE PROCEDURE [dbo].[PR_TRANS_DETAIL_LIST_BY_GB]
( 
	@P_SEARCH_TYPE			NVARCHAR(1) = '',			-- 조회구분 1: 운송구간별 2: 차량중량별 3: 배송지별 4: 차량번호별
	@P_VEN_CODE				NVARCHAR(7) = '',			-- 거래처코드
	@P_IO_GB				INT,						-- 입출고구분 1: 입고 2: 출고
	@P_START_DT				NVARCHAR(8) = '',			-- 조회시작일자
	@P_END_DT				NVARCHAR(8) = '',			-- 조회종료일자
	@P_TRANS_SECTION		NVARCHAR(6) = '',			-- 운송구간
	@P_CAR_GB				NVARCHAR(1) = '',			-- 차량구분
	@P_UP_DELIVERY_CODE		NVARCHAR(7) = '',			-- 상위배송지코드
	@P_CAR_NO				NVARCHAR(8) = ''			-- 차량번호

)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	BEGIN TRY
		BEGIN
			SELECT A.DELIVERY_DT,
				   A.ORD_DT,
					A.ORD_NO,
					A.CAR_NO,
					A.NET_WGHT,
					A.OFFICIAL_WGHT,
					(A.PLT_QTY11 + A.PLT_QTY12) AS PLT_QTY,
					A.TRANS_COST,
					A.RENT_COST,
					(A.TRANS_COST - A.RENT_COST) AS FEE,
					B.DELIVERY_REQ_DT,
					ISNULL(C.TRANS_SECTION, '') AS TRANS_SECTION,
					(SELECT ISNULL(DELIVERY_NAME, '')
						FROM CD_PARTNER_DELIVERY 
						WHERE VEN_CODE = D.VEN_CODE AND DELIVERY_CODE = CONCAT(LEFT(D.DELIVERY_CODE,6), '1')) AS UP_DELIVERY_NAME,
					ISNULL(D.DELIVERY_NAME, '') AS DELIVERY_NAME,
					ISNULL(E.CD_NM,'') AS CAR_GB_NM
			FROM PO_SCALE A
				INNER JOIN PO_ORDER_HDR B ON A.ORD_NO = B.ORD_NO
				LEFT OUTER JOIN CD_DELIVERY_PRICE C ON B.DELIVERY_PRICE_SEQ = C.SEQ
				LEFT OUTER JOIN CD_PARTNER_DELIVERY D ON D.VEN_CODE = B.VEN_CODE AND D.DELIVERY_CODE = B.DELIVERY_CODE
				LEFT OUTER JOIN TBL_COMM_CD_MST E ON E.CD_CL = 'CAR_GB' AND E.CD_ID = A.CAR_GB
			WHERE B.ORD_STAT IN ('33', '35', '40')
				  --AND ISNULL(A.TRANS_COST, 0) <> 0
				  AND 1 = (CASE WHEN @P_SEARCH_TYPE = '1' AND @P_TRANS_SECTION <> '' AND C.TRANS_SECTION = @P_TRANS_SECTION THEN 1 
								WHEN @P_SEARCH_TYPE = '1' AND @P_TRANS_SECTION = '' AND ISNULL(C.TRANS_SECTION, '') = '' THEN 1 
								WHEN @P_SEARCH_TYPE = '2' AND @P_CAR_GB <> '' AND A.CAR_GB = @P_CAR_GB THEN 1	
								WHEN @P_SEARCH_TYPE = '2' AND @P_CAR_GB = '' AND ISNULL(A.CAR_GB, '') = '' THEN 1	
								WHEN @P_SEARCH_TYPE = '3' AND CONCAT(LEFT(B.DELIVERY_CODE,6), '1') = @P_UP_DELIVERY_CODE THEN 1
								WHEN @P_SEARCH_TYPE = '3' AND @P_UP_DELIVERY_CODE = '' AND (B.DELIVERY_CODE = '' OR B.DELIVERY_CODE IS NULL) THEN 1
								WHEN @P_SEARCH_TYPE = '4' AND @P_CAR_NO = '' AND A.CAR_NO IS NULL THEN 1
								WHEN @P_SEARCH_TYPE = '4' AND A.CAR_NO = @P_CAR_NO THEN 1
								ELSE 0 END)
				  AND 1 = (CASE WHEN @P_IO_GB = 2 THEN 2 ELSE 1 END)
				  AND 1 = (CASE WHEN @P_VEN_CODE = '' THEN 1 WHEN  @P_VEN_CODE <> '' AND @P_VEN_CODE = A.VEN_CODE THEN 1 ELSE 0 END )
				  AND 1 = (CASE WHEN @P_START_DT != '' AND A.DELIVERY_DT BETWEEN @P_START_DT AND @P_END_DT THEN 1 ELSE 0 END) 
			UNION ALL
			SELECT A.DELIVERY_DT,
					A.ORD_DT,
					A.ORD_NO,
					A.CAR_NO,
					A.NET_WGHT,
					A.OFFICIAL_WGHT,
					(A.PLT_QTY11 + A.PLT_QTY12) AS PLT_QTY,
					A.TRANS_COST,
					A.RENT_COST,
					(A.TRANS_COST - A.RENT_COST) AS FEE,
					B.ORD_DT AS DELIVERY_REQ_DT,
					ISNULL(C.TRANS_SECTION, '') AS TRANS_SECTION,
					(SELECT ISNULL(DELIVERY_NAME, '')
						FROM CD_PARTNER_DELIVERY 
						WHERE VEN_CODE = D.VEN_CODE AND DELIVERY_CODE = CONCAT(LEFT(D.DELIVERY_CODE,6), '1')) AS UP_DELIVERY_NAME,
					ISNULL(D.DELIVERY_NAME, '') AS DELIVERY_NAME,
					ISNULL(E.CD_NM,'') AS CAR_GB_NM
			FROM PO_SCALE A
				INNER JOIN PO_PURCHASE_HDR B ON A.ORD_NO = B.ORD_NO
				LEFT OUTER JOIN CD_DELIVERY_PRICE C ON B.DELIVERY_PRICE_SEQ = C.SEQ
				LEFT OUTER JOIN CD_PARTNER_DELIVERY D ON D.VEN_CODE = B.VEN_CODE AND D.DELIVERY_CODE = B.DELIVERY_CODE
				LEFT OUTER JOIN TBL_COMM_CD_MST E ON E.CD_CL = 'CAR_GB' AND E.CD_ID = A.CAR_GB
			WHERE B.PUR_STAT IN ('33', '35', '40')
				  --AND ISNULL(A.TRANS_COST, 0) <> 0
				  AND 1 = (CASE WHEN @P_SEARCH_TYPE = '1' AND @P_TRANS_SECTION <> '' AND C.TRANS_SECTION = @P_TRANS_SECTION THEN 1 
								WHEN @P_SEARCH_TYPE = '1' AND @P_TRANS_SECTION = '' AND ISNULL(C.TRANS_SECTION, '') = '' THEN 1 
								WHEN @P_SEARCH_TYPE = '2' AND @P_CAR_GB <> '' AND A.CAR_GB = @P_CAR_GB THEN 1	
								WHEN @P_SEARCH_TYPE = '2' AND @P_CAR_GB = '' AND ISNULL(A.CAR_GB, '') = '' THEN 1	
				  			    WHEN @P_SEARCH_TYPE = '3' AND CONCAT(LEFT(B.DELIVERY_CODE,6), '1') = @P_UP_DELIVERY_CODE THEN 1
				  			    WHEN @P_SEARCH_TYPE = '3' AND @P_UP_DELIVERY_CODE = '' AND (B.DELIVERY_CODE = '' OR B.DELIVERY_CODE IS NULL) THEN 1
				  			    WHEN @P_SEARCH_TYPE = '4' AND @P_CAR_NO = '' AND A.CAR_NO IS NULL THEN 1
				  			    WHEN @P_SEARCH_TYPE = '4' AND A.CAR_NO = @P_CAR_NO THEN 1
				  			    ELSE 0 END)
				  AND 1 = (CASE WHEN @P_IO_GB = 2 THEN 2 ELSE 1 END)
				  AND 1 = (CASE WHEN @P_VEN_CODE = '' THEN 1 WHEN  @P_VEN_CODE <> '' AND @P_VEN_CODE = A.VEN_CODE THEN 1 ELSE 0 END )
				  AND 1 = (CASE WHEN @P_START_DT != '' AND A.DELIVERY_DT BETWEEN @P_START_DT AND @P_END_DT THEN 1 ELSE 0 END) 
		END
		 
	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
	
END

GO

