/*
-- 생성자 :	강세미
-- 등록일 :	2024.05.03
-- 수정자 : 2024.09.02 강세미 - 조회조건 추가(차량번호)
-- 수정일 : - 
-- 설 명  : 배차내역조회
-- 실행문 : 
EXEC PR_TRANS_LIST_BY_GB '3','', '', '20240404', '20241011'
*/
CREATE PROCEDURE [dbo].[PR_TRANS_LIST_BY_GB]
( 
	@P_SEARCH_TYPE	NVARCHAR(1) = '',			-- 조회구분 1: 운송구간별 2: 차량중량별 3: 배송지별 4: 차량번호별
	@P_VEN_CODE		NVARCHAR(7) = '',			-- 거래처코드
	@P_IO_GB		INT,						-- 입출고구분 1: 입고 2: 출고
	@P_START_DT		NVARCHAR(8) = '',			-- 조회시작일자
	@P_END_DT		NVARCHAR(8) = '',			-- 조회종료일자
	@P_CAR_NO		NVARCHAR(8) = ''			-- 차량번호
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	BEGIN TRY
		IF @P_SEARCH_TYPE = '1' -- 운송구간별
			BEGIN
				WITH COM_DATA AS (
					 SELECT D.TRANS_SECTION,
						   COUNT(*) AS COUNT,
						   ISNULL(SUM(A.TRANS_COST),0) AS TRANS_COST,
						   ISNULL(SUM(A.RENT_COST),0) AS RENT_COST,
						   ISNULL(SUM(A.TRANS_COST),0) - ISNULL(SUM(A.RENT_COST),0) AS FEE
					 FROM PO_SCALE A
						 INNER JOIN PO_ORDER_HDR B ON A.ORD_NO = B.ORD_NO
						 --LEFT OUTER JOIN CD_PARTNER_DELIVERY C ON B.VEN_CODE = C.VEN_CODE AND B.DELIVERY_CODE = C.DELIVERY_CODE
						 LEFT OUTER JOIN CD_DELIVERY_PRICE D ON B.DELIVERY_PRICE_SEQ = D.SEQ	 
					 WHERE 1=1
						 --AND D.TRANS_SECTION IS NOT NULL
						 --AND A.TRANS_COST != 0
						 AND B.ORD_STAT IN ('33', '35', '40')
						 AND 1 = (CASE WHEN @P_IO_GB = 1 THEN 2 ELSE 1 END)	
						 AND 1 = (CASE WHEN @P_VEN_CODE = '' THEN 1 WHEN  @P_VEN_CODE <> '' AND @P_VEN_CODE = A.VEN_CODE THEN 1 ELSE 0 END )
						 AND 1 = (CASE WHEN @P_START_DT != '' AND A.DELIVERY_DT BETWEEN @P_START_DT AND @P_END_DT THEN 1 ELSE 0 END)
						 AND 1 = (CASE WHEN @P_CAR_NO = '' THEN 1 WHEN  @P_CAR_NO <> '' AND A.CAR_NO LIKE '%' + @P_CAR_NO + '%' THEN 1 ELSE 0 END )
					 GROUP BY D.TRANS_SECTION
					 UNION
					 SELECT D.TRANS_SECTION,
						   COUNT(*) AS COUNT,
				 		   ISNULL(SUM(A.TRANS_COST),0) AS TRANS_COST,
				 		   ISNULL(SUM(A.RENT_COST),0) AS RENT_COST,
						   ISNULL(SUM(A.TRANS_COST),0) - ISNULL(SUM(A.RENT_COST),0) AS FEE
					 FROM PO_SCALE A
						 INNER JOIN PO_PURCHASE_HDR B ON A.ORD_NO = B.ORD_NO
						 --LEFT OUTER JOIN CD_PARTNER_DELIVERY C ON B.VEN_CODE = C.VEN_CODE AND B.DELIVERY_CODE = C.DELIVERY_CODE
						 LEFT OUTER JOIN CD_DELIVERY_PRICE D ON B.DELIVERY_PRICE_SEQ = D.SEQ
					 WHERE 1=1
						 --AND ISNULL(D.TRANS_SECTION,'') <> ''
						 --AND ISNULL(A.TRANS_COST, 0) <> 0
						 AND B.PUR_STAT IN ('33', '35', '40')
						 AND 1 = (CASE WHEN @P_IO_GB = 2 THEN 2 ELSE 1 END)
						 AND 1 = (CASE WHEN @P_VEN_CODE = '' THEN 1 WHEN  @P_VEN_CODE <> '' AND @P_VEN_CODE = A.VEN_CODE THEN 1 ELSE 0 END )
						 AND 1 = (CASE WHEN @P_START_DT != '' AND A.DELIVERY_DT BETWEEN @P_START_DT AND @P_END_DT THEN 1 ELSE 0 END)
						 AND 1 = (CASE WHEN @P_CAR_NO = '' THEN 1 WHEN  @P_CAR_NO <> '' AND A.CAR_NO LIKE '%' + @P_CAR_NO + '%' THEN 1 ELSE 0 END )
					 GROUP BY D.TRANS_SECTION
				)
				SELECT TRANS_SECTION,
					   SUM(COUNT) AS COUNT,
					   SUM(TRANS_COST) AS TRANS_COST,
					   SUM(RENT_COST) AS RENT_COST,
					   SUM(FEE) AS FEE
				FROM COM_DATA
				GROUP BY TRANS_SECTION;
			END
		ELSE IF @P_SEARCH_TYPE = '2' -- 차량중량별
			BEGIN
				
				WITH COM_DATA AS (
					SELECT ISNULL(A.CAR_GB, '') AS CAR_GB,
						   ISNULL(D.CD_NM, '') AS CAR_GB_NM,
						   COUNT(*) AS COUNT,
						   SUM(ISNULL(A.TRANS_COST, 0)) AS TRANS_COST,
						   SUM(ISNULL(A.RENT_COST, 0)) AS RENT_COST,
						   SUM(ISNULL(A.TRANS_COST, 0)) - SUM(ISNULL(A.RENT_COST,0)) AS FEE
					FROM PO_SCALE A 
						INNER JOIN PO_ORDER_HDR B ON A.ORD_NO = B.ORD_NO AND B.ORD_STAT IN ('33', '35', '40')
						LEFT OUTER JOIN TBL_COMM_CD_MST D ON D.CD_CL = 'CAR_GB' AND D.CD_ID = A.CAR_GB
					WHERE 1=1
					--ISNULL(A.TRANS_COST, 0) <> 0
						  AND 1 = (CASE WHEN @P_IO_GB = 1 THEN 2 ELSE 1 END)	
						  AND 1 = (CASE WHEN @P_VEN_CODE = '' THEN 1 WHEN  @P_VEN_CODE <> '' AND @P_VEN_CODE = A.VEN_CODE THEN 1 ELSE 0 END )
						  AND 1 = (CASE WHEN @P_START_DT != '' AND A.DELIVERY_DT BETWEEN @P_START_DT AND @P_END_DT THEN 1 ELSE 0 END)
						  AND 1 = (CASE WHEN @P_CAR_NO = '' THEN 1 WHEN  @P_CAR_NO <> '' AND A.CAR_NO LIKE '%' + @P_CAR_NO + '%' THEN 1 ELSE 0 END )
					GROUP BY A.CAR_GB, D.CD_NM
					UNION ALL
					SELECT ISNULL(A.CAR_GB, '') AS CAR_GB,
						   ISNULL(D.CD_NM, '') AS CAR_GB_NM,
						   COUNT(*) AS COUNT,
						   SUM(ISNULL(A.TRANS_COST, 0)) AS TRANS_COST,
						   SUM(ISNULL(A.RENT_COST, 0)) AS RENT_COST,
						   SUM(ISNULL(A.TRANS_COST, 0)) - SUM(ISNULL(A.RENT_COST,0)) AS FEE
					FROM PO_SCALE A 
						INNER JOIN PO_PURCHASE_HDR B ON A.ORD_NO = B.ORD_NO AND B.PUR_STAT IN ('33', '35', '40')
						LEFT OUTER JOIN TBL_COMM_CD_MST D ON D.CD_CL = 'CAR_GB' AND D.CD_ID = A.CAR_GB
					WHERE 1=1
					--ISNULL(A.TRANS_COST, 0) <> 0
						  AND 1 = (CASE WHEN @P_IO_GB = 2 THEN 2 ELSE 1 END)
						  AND 1 = (CASE WHEN @P_VEN_CODE = '' THEN 1 WHEN  @P_VEN_CODE <> '' AND @P_VEN_CODE = A.VEN_CODE THEN 1 ELSE 0 END )
						  AND 1 = (CASE WHEN @P_START_DT != '' AND A.DELIVERY_DT BETWEEN @P_START_DT AND @P_END_DT THEN 1 ELSE 0 END)
						  AND 1 = (CASE WHEN @P_CAR_NO = '' THEN 1 WHEN  @P_CAR_NO <> '' AND A.CAR_NO LIKE '%' + @P_CAR_NO + '%' THEN 1 ELSE 0 END )
					GROUP BY A.CAR_GB, D.CD_NM
				)
				SELECT CAR_GB,
					   CAR_GB_NM,
					   SUM(COUNT) AS COUNT,
					   SUM(TRANS_COST) AS TRANS_COST,
					   SUM(RENT_COST) AS RENT_COST,
					   SUM(FEE) AS FEE
				FROM COM_DATA
				GROUP BY CAR_GB, CAR_GB_NM;
			END
		ELSE IF @P_SEARCH_TYPE = '3' -- 배송지별
			BEGIN

				WITH LIST AS (
					SELECT 
						(CASE WHEN CC.DELIVERY_CODE IS NULL OR CC.DELIVERY_CODE = '' THEN '' 
							  ELSE CONCAT(LEFT(CC.DELIVERY_CODE,6), '1') END) AS UP_DELIVERY_CODE, 
						(CASE WHEN RIGHT(CC.DELIVERY_CODE, 1) = '1' THEN DELIVERY_NAME 
							  WHEN CC.DELIVERY_CODE IS NULL OR CC.DELIVERY_CODE = '' THEN '주문_수기입력'
							  ELSE (SELECT DELIVERY_NAME 
									FROM CD_PARTNER_DELIVERY 
									WHERE VEN_CODE = CC.VEN_CODE AND DELIVERY_CODE = CONCAT(LEFT(CC.DELIVERY_CODE,6), '1')) END) AS UP_DELIVERY_NAME,
						CC.DELIVERY_CODE,
						CC.DELIVERY_NAME,
						BB.VEN_CODE,
						DD.VEN_NAME,
						COUNT(*) AS COUNT,
						ISNULL(SUM(AA.TRANS_COST),0) AS TRANS_COST,
						ISNULL(SUM(AA.RENT_COST),0) AS RENT_COST,
						ISNULL(SUM(AA.TRANS_COST),0) - ISNULL(SUM(AA.RENT_COST),0) AS FEE
					FROM PO_SCALE AA
						INNER JOIN PO_ORDER_HDR BB ON AA.ORD_NO = BB.ORD_NO
						LEFT OUTER JOIN CD_PARTNER_DELIVERY CC ON BB.VEN_CODE = CC.VEN_CODE AND BB.DELIVERY_CODE = CC.DELIVERY_CODE
						INNER JOIN CD_PARTNER_MST DD ON AA.VEN_CODE = DD.VEN_CODE
					WHERE 1=1
					-- ISNULL(AA.TRANS_COST, 0) <> 0
						AND BB.ORD_STAT IN ('33', '35', '40')
						AND 1 = (CASE WHEN @P_IO_GB = 1 THEN 2 ELSE 1 END)	
						AND 1 = (CASE WHEN @P_VEN_CODE = '' THEN 1 WHEN  @P_VEN_CODE <> '' AND @P_VEN_CODE = AA.VEN_CODE THEN 1 ELSE 0 END )
						AND 1 = (CASE WHEN @P_START_DT != '' AND AA.DELIVERY_DT BETWEEN @P_START_DT AND @P_END_DT THEN 1 ELSE 0 END)
						AND 1 = (CASE WHEN @P_CAR_NO = '' THEN 1 WHEN  @P_CAR_NO <> '' AND AA.CAR_NO LIKE '%' + @P_CAR_NO + '%' THEN 1 ELSE 0 END )
					GROUP BY BB.VEN_CODE, CC.VEN_CODE, CC.DELIVERY_CODE, CC.DELIVERY_NAME, DD.VEN_NAME
				UNION ALL
					SELECT 
						(CASE WHEN CC.DELIVERY_CODE IS NULL OR CC.DELIVERY_CODE = '' THEN '' 
							  ELSE CONCAT(LEFT(CC.DELIVERY_CODE,6), '1') END) AS UP_DELIVERY_CODE, 
						(CASE WHEN RIGHT(CC.DELIVERY_CODE, 1) = '1' THEN DELIVERY_NAME 
							  WHEN CC.DELIVERY_CODE IS NULL OR CC.DELIVERY_CODE = '' THEN '발주_수기입력'
							  ELSE (SELECT DELIVERY_NAME 
									FROM CD_PARTNER_DELIVERY 
									WHERE VEN_CODE = CC.VEN_CODE AND DELIVERY_CODE = CONCAT(LEFT(CC.DELIVERY_CODE,6), '1')) END) AS UP_DELIVERY_NAME,
						CC.DELIVERY_CODE,
						CC.DELIVERY_NAME,
						BB.VEN_CODE,
						DD.VEN_NAME,
						COUNT(*) AS COUNT,
						ISNULL(SUM(AA.TRANS_COST),0) AS TRANS_COST,
						ISNULL(SUM(AA.RENT_COST),0) AS RENT_COST,
						ISNULL(SUM(AA.TRANS_COST),0) - ISNULL(SUM(AA.RENT_COST),0) AS FEE
					FROM PO_SCALE AA
						INNER JOIN PO_PURCHASE_HDR BB ON AA.ORD_NO = BB.ORD_NO
						LEFT OUTER JOIN CD_PARTNER_DELIVERY CC ON BB.VEN_CODE = CC.VEN_CODE AND BB.DELIVERY_CODE = CC.DELIVERY_CODE
						INNER JOIN CD_PARTNER_MST DD ON AA.VEN_CODE = DD.VEN_CODE
					WHERE 1=1
					--ISNULL(AA.TRANS_COST, 0) <> 0
						AND BB.PUR_STAT IN ('33', '35', '40')
						AND 1 = (CASE WHEN @P_IO_GB = 1 THEN 2 ELSE 1 END)	
						AND 1 = (CASE WHEN @P_VEN_CODE = '' THEN 1 WHEN  @P_VEN_CODE <> '' AND @P_VEN_CODE = AA.VEN_CODE THEN 1 ELSE 0 END )
						AND 1 = (CASE WHEN @P_START_DT != '' AND AA.DELIVERY_DT BETWEEN @P_START_DT AND @P_END_DT THEN 1 ELSE 0 END)
						AND 1 = (CASE WHEN @P_CAR_NO = '' THEN 1 WHEN  @P_CAR_NO <> '' AND AA.CAR_NO LIKE '%' + @P_CAR_NO + '%' THEN 1 ELSE 0 END )
					GROUP BY BB.VEN_CODE, CC.VEN_CODE, CC.DELIVERY_CODE, CC.DELIVERY_NAME, DD.VEN_NAME
				)  
				SELECT 
					A.UP_DELIVERY_CODE,
					A.UP_DELIVERY_NAME,
					A.VEN_CODE,
					A.VEN_NAME,
					SUM(COUNT) AS COUNT,
					ISNULL(SUM(A.TRANS_COST),0) AS TRANS_COST,
					ISNULL(SUM(A.RENT_COST),0) AS RENT_COST,
					ISNULL(SUM(A.TRANS_COST),0) - ISNULL(SUM(A.RENT_COST),0) AS FEE
				FROM LIST AS A
				GROUP BY A.UP_DELIVERY_CODE, A.UP_DELIVERY_NAME, A.VEN_CODE, A.VEN_NAME
				ORDER BY VEN_NAME

			END
		ELSE -- 차량번호별
			BEGIN
			
				WITH COM_DATA AS (
					SELECT (CASE WHEN A.CAR_NO IS NULL THEN '' ELSE A.CAR_NO END) AS CAR_NO,
						   COUNT(*) AS COUNT,
						   SUM(A.TRANS_COST) AS TRANS_COST,
						   SUM(A.RENT_COST) AS RENT_COST,
						   ISNULL(SUM(A.TRANS_COST),0) - ISNULL(SUM(A.RENT_COST),0) AS FEE
					FROM PO_SCALE A
						INNER JOIN PO_ORDER_HDR B ON A.ORD_NO = B.ORD_NO AND B.ORD_STAT IN ('33', '35', '40')
					WHERE 1=1
					--ISNULL(A.TRANS_COST, 0) <> 0
						 AND 1 = (CASE WHEN @P_IO_GB = 1 THEN 2 ELSE 1 END)	
						 AND 1 = (CASE WHEN @P_VEN_CODE = '' THEN 1 WHEN  @P_VEN_CODE <> '' AND @P_VEN_CODE = A.VEN_CODE THEN 1 ELSE 0 END )
						 AND 1 = (CASE WHEN @P_START_DT != '' AND A.DELIVERY_DT BETWEEN @P_START_DT AND @P_END_DT THEN 1 ELSE 0 END)
						 AND 1 = (CASE WHEN @P_CAR_NO = '' THEN 1 WHEN  @P_CAR_NO <> '' AND A.CAR_NO LIKE '%' + @P_CAR_NO + '%' THEN 1 ELSE 0 END )
					GROUP BY (CASE WHEN A.CAR_NO IS NULL THEN '' ELSE A.CAR_NO END)
					UNION ALL
					SELECT (CASE WHEN A.CAR_NO IS NULL THEN '' ELSE A.CAR_NO END) AS CAR_NO,
						   COUNT(*) AS COUNT,
						   SUM(A.TRANS_COST) AS TRANS_COST,
						   SUM(A.RENT_COST) AS RENT_COST,
						   ISNULL(SUM(A.TRANS_COST),0) - ISNULL(SUM(A.RENT_COST),0) AS FEE
					FROM PO_SCALE A
						INNER JOIN PO_PURCHASE_HDR B ON A.ORD_NO = B.ORD_NO AND B.PUR_STAT IN ('33', '35', '40')
					WHERE 1=1
					--ISNULL(A.TRANS_COST, 0) <> 0
						 AND 1 = (CASE WHEN @P_IO_GB = 1 THEN 2 ELSE 1 END)	
						 AND 1 = (CASE WHEN @P_VEN_CODE = '' THEN 1 WHEN  @P_VEN_CODE <> '' AND @P_VEN_CODE = A.VEN_CODE THEN 1 ELSE 0 END )
						 AND 1 = (CASE WHEN @P_START_DT != '' AND A.DELIVERY_DT BETWEEN @P_START_DT AND @P_END_DT THEN 1 ELSE 0 END)
						 AND 1 = (CASE WHEN @P_CAR_NO = '' THEN 1 WHEN  @P_CAR_NO <> '' AND A.CAR_NO LIKE '%' + @P_CAR_NO + '%' THEN 1 ELSE 0 END )
					GROUP BY (CASE WHEN A.CAR_NO IS NULL THEN '' ELSE A.CAR_NO END)
				)
				SELECT CAR_NO,
					   SUM(COUNT) AS COUNT,
					   SUM(TRANS_COST) AS TRANS_COST,
					   SUM(RENT_COST) AS RENT_COST,
					   SUM(FEE) AS FEE
				FROM COM_DATA
				GROUP BY CAR_NO;
			END
	
	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
	
END

GO

