/*
-- 생성자 :	강세미
-- 등록일 :	2024.01.05
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 사용자 비밀번호 초기화
-- 실행문 : EXEC PR_USER_MST_PW_RESET 'id','admin'
*/
CREATE PROCEDURE [dbo].[PR_USER_MST_PW_RESET]
	@P_USER_ID NVARCHAR(20),	-- 사용자ID
	@P_UEMP_ID NVARCHAR(20) 	-- 수정아이디
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	DECLARE @PASSWD_NO BINARY(20)			-- 비밀번호
	DECLARE @RETURN_CODE INT = 0			-- 리턴코드
	DECLARE @RETURN_MESSAGE NVARCHAR(10) = ''		-- 리턴메시지

	BEGIN TRY 
		SET @PASSWD_NO = CONVERT(BINARY(20), HASHBYTES('SHA1',@P_USER_ID))

		UPDATE TBL_USER_MST
			SET PASSWD_NO = @PASSWD_NO,
				 PWD_COUNT = 0,
				 UDATE = GETDATE(),
				 UEMP_ID = @P_UEMP_ID
		 WHERE USER_ID = @P_USER_ID
		
		SET @RETURN_CODE = 0
		SET @RETURN_MESSAGE = '저장되었습니다.'

	END TRY
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	

		SET @RETURN_CODE = -1
		SET @RETURN_MESSAGE = '저장 실패하였습니다.'
	END CATCH
	
	
	SELECT @RETURN_CODE AS RETURN_CODE, @RETURN_MESSAGE AS RETURN_MESSAGE
END

GO

