/*
-- 생성자 :	강세미
-- 등록일 :	2023.01.10
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 사용자별 메뉴 출력
-- 실행문 : 
EXEC PR_USER_ROLE_MENU_LIST 'admin'
*/
CREATE PROCEDURE [dbo].[PR_USER_ROLE_MENU_LIST]
( @P_USER_ID NVARCHAR(20) = '' -- 사용자ID
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	BEGIN TRY 
		SELECT ROW_NUMBER() OVER(ORDER BY A.MENU_CODE) AS ROW_NUM
			  , [USER_ID]
			  , A.MENU_CODE
			  , B.MENU_NM
			  , 'Y' AS USE_YN	 
		  FROM TBL_USER_ROLE_MST AS A
			INNER JOIN TBL_MENU_INFO AS B
			ON B.MENU_CODE = A.MENU_CODE
		 WHERE USER_ID = @P_USER_ID
		 UNION ALL
		SELECT ROW_NUMBER() OVER(ORDER BY A.MENU_CODE) AS ROW_NUM
			  , @P_USER_ID
			  , A.MENU_CODE
			  , A.MENU_NM
			  , 'N' AS USE_YN
		  FROM TBL_MENU_INFO AS A
		 WHERE A.MENU_CODE NOT IN 
				(SELECT MENU_CODE
					FROM TBL_USER_ROLE_MST
				  WHERE USER_ID = @P_USER_ID)
			AND A.MENU_LINK != ''
			AND A.DEL_YN = 'N'
	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
	
END

GO

