
/*

-- 생성자 :	이동호
-- 등록일 :	2024.11.28
-- 수정자 : -
-- 수정일 : -
-- 설 명  : 프로시저 백업 관리 
			프로시저 작업 전에 한번 백업하고 진행
-- 실행문 : 

EXEC SP_PROC_BACKUP 'PR_ACCT_DEPOSIT_MANUAL_PUT', '이동호'

SELECT * FROM TBL_PROC_BACKUP

*/
CREATE PROCEDURE [dbo].[SP_PROC_BACKUP]
( 	
	@P_PROC_NAME			NVARCHAR(150),	--프로시저 이름
	@P_USER_NM				NVARCHAR(150)	--백업자 이름	
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	
	DECLARE @RETURN_CODE INT = 0
	DECLARE @RETURN_MESSAGE NVARCHAR(MAX) = ''
	
	BEGIN TRY 
			
		DECLARE @PROC_TEXT NVARCHAR(MAX) = ''
		
		SELECT @PROC_TEXT = OBJECT_DEFINITION(OBJECT_ID(@P_PROC_NAME))

		INSERT INTO TBL_PROC_BACKUP (PROC_NM, PROC_TEXT, IEMP_NM, IDATE) VALUES (@P_PROC_NAME, @PROC_TEXT, @P_USER_NM, GETDATE())

		SET @PROC_TEXT = ''

	END TRY
	BEGIN CATCH	
				
		SET @RETURN_CODE = -1
		SET @RETURN_MESSAGE = ERROR_MESSAGE()
		
	END CATCH
	
	SELECT @RETURN_CODE AS RETURN_CODE, @RETURN_MESSAGE AS RETURN_MESSAGE
END

GO

