/*
-- 생성자 :	윤현빈
-- 등록일 :	2024.08.29
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 입고/출고일보
-- 실행문 : EXEC PR_ANALYSIS_DAILY_ORD_PUR_LIST '','','','',''
*/
CREATE PROCEDURE [dbo].[PR_ANALYSIS_DAILY_ORD_PUR_LIST]
( 
	@P_REPORT_DATE		NVARCHAR(8) = '',	-- 거래처코드
	@P_LOT_OIL_GB		NVARCHAR(2) = '',	-- 유종
	@P_LOT_PARTNER_GB	NVARCHAR(3) = '',	-- 거래처 구분
	@P_TAB_INDEX	 	NVARCHAR(1) = ''	-- 중분류 코드
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	BEGIN TRY 	
----------------------------------------------------
-- 원재료 입고 조회
----------------------------------------------------
		IF @P_TAB_INDEX = '1'
		BEGIN
			SELECT ROW_NUMBER() OVER(ORDER BY A.REPORT_DATE, A.VEN_CODE, A.SCAN_CODE) AS ROW_NUM
			     , A.REPORT_DATE
			     , A.VEN_CODE
			     , C.VEN_NAME
			     , A.SCAN_CODE
				 , B.WEIGHT_GB
			     , B.ITM_NAME
			     --, A.PUR_QTY
				 , CASE WHEN B.WEIGHT_GB = 'QTY' THEN CONCAT(CAST(FORMAT(A.PUR_QTY, 'N0') AS NVARCHAR(13)), ' EA') WHEN B.WEIGHT_GB = 'WT' THEN CONCAT(CAST(FORMAT(A.PUR_QTY, 'N0') AS NVARCHAR(13)), ' KG') ELSE CAST(FORMAT(A.PUR_QTY, 'N0') AS NVARCHAR(13)) END AS PUR_QTY
				 , ISNULL(A.REMARKS, '') AS REMARKS
				FROM RP_ANALYSIS_DAILY_PUR AS A
				INNER JOIN CD_PRODUCT_CMN AS B ON A.SCAN_CODE = B.SCAN_CODE
				INNER JOIN CD_PARTNER_MST AS C ON A.VEN_CODE = C.VEN_CODE
			   WHERE A.REPORT_DATE = @P_REPORT_DATE
			     AND 1=(CASE WHEN @P_LOT_OIL_GB = '' THEN 1 WHEN @P_LOT_OIL_GB != '' AND @P_LOT_OIL_GB = B.LOT_OIL_GB THEN 1 ELSE 2 END)
				 AND B.ITM_GB = '2'
		END

----------------------------------------------------
-- 부자재 입고 조회
----------------------------------------------------
		ELSE IF @P_TAB_INDEX = '2'
		BEGIN
			SELECT ROW_NUMBER() OVER(ORDER BY A.REPORT_DATE, A.VEN_CODE, A.SCAN_CODE) AS ROW_NUM
			     , A.REPORT_DATE
			     , A.VEN_CODE
			     , C.VEN_NAME
			     , A.SCAN_CODE
				 , B.WEIGHT_GB
			     , B.ITM_NAME
			     --, A.PUR_QTY
				 , CASE WHEN B.WEIGHT_GB = 'QTY' THEN CONCAT(CAST(FORMAT(A.PUR_QTY, 'N0') AS NVARCHAR(13)), ' EA') WHEN B.WEIGHT_GB = 'WT' THEN CONCAT(CAST(FORMAT(A.PUR_QTY, 'N0') AS NVARCHAR(13)), ' KG') ELSE CAST(FORMAT(A.PUR_QTY, 'N0') AS NVARCHAR(13)) END AS PUR_QTY
				 , ISNULL(A.REMARKS, '') AS REMARKS
				FROM RP_ANALYSIS_DAILY_PUR AS A
				INNER JOIN CD_PRODUCT_CMN AS B ON A.SCAN_CODE = B.SCAN_CODE
				INNER JOIN CD_PARTNER_MST AS C ON A.VEN_CODE = C.VEN_CODE
			   WHERE A.REPORT_DATE = @P_REPORT_DATE
			     AND B.ITM_GB = '3'

		END

----------------------------------------------------
-- 제품 출고 조회
----------------------------------------------------
		ELSE IF @P_TAB_INDEX = '3'
		BEGIN
			SELECT ROW_NUMBER() OVER(ORDER BY A.REPORT_DATE, A.VEN_CODE, A.DELIVERY_CODE, A.SCAN_CODE) AS ROW_NUM
			     , A.REPORT_DATE
			     , A.VEN_CODE
			     , C.VEN_NAME
				 , D.CD_NM AS LOT_PARTNER_GB_NM
				 , ISNULL(F.DELIVERY_NAME, '-') AS UP_DELIVERY_NAME
				 , ISNULL(E.DELIVERY_NAME, '-') AS DELIVERY_NAME
			     , A.SCAN_CODE
				 , B.WEIGHT_GB
			     , B.ITM_NAME
				 --, A.ORD_QTY
				 --, CASE WHEN B.WEIGHT_GB = 'QTY' THEN CONCAT(A.ORD_QTY, ' EA') WHEN B.WEIGHT_GB = 'WT' THEN CONCAT(A.ORD_QTY, ' KG') ELSE A.ORD_QTY END AS ORD_QTY
				 , CASE WHEN B.WEIGHT_GB = 'QTY' THEN CONCAT(CAST(FORMAT(A.ORD_QTY, 'N0') AS NVARCHAR(13)), ' EA') WHEN B.WEIGHT_GB = 'WT' THEN CONCAT(CAST(FORMAT(A.ORD_QTY, 'N0') AS NVARCHAR(13)), ' KG') ELSE CAST(FORMAT(A.ORD_QTY, 'N0') AS NVARCHAR(13)) END AS ORD_QTY
				 , CASE WHEN B.ITM_FORM = '2' THEN CONCAT(CAST(A.ORD_QTY AS INT), ' BOX') WHEN B.ITM_FORM = '1' AND B.MID_CODE = '0302' THEN CONCAT(CAST(ROUND(A.ORD_QTY / B.IPSU_QTY, 0) AS INT), ' BOX') ELSE '' END AS BOX_QTY
				 --, CONCAT(1, ' BOX') AS BOX_QTY
			  --   , A.ORD_QTY
				 --, (CASE WHEN B.ITM_FORM = '2' THEN )
				 --, (CASE WHEN B.ITM_FORM = '2' THEN A.ORD_QTY * ISNULL(G.IPSU_QTY, 0) ELSE 0 END) AS BOX_QTY
				FROM RP_ANALYSIS_DAILY_ORD AS A
				INNER JOIN CD_PRODUCT_CMN AS B ON A.SCAN_CODE = B.SCAN_CODE
				INNER JOIN CD_PARTNER_MST AS C ON A.VEN_CODE = C.VEN_CODE
				INNER JOIN TBL_COMM_CD_MST AS D ON B.LOT_PARTNER_GB = D.CD_ID AND D.CD_CL = 'LOT_PARTNER_GB'
				LEFT OUTER JOIN CD_PARTNER_DELIVERY AS E ON A.DELIVERY_CODE = E.DELIVERY_CODE AND E.USE_YN = 'Y'
				LEFT OUTER JOIN CD_PARTNER_DELIVERY AS F ON A.VEN_CODE = F.VEN_CODE AND F.DELIVERY_CODE = CONCAT(LEFT(E.DELIVERY_CODE,6), '1')
				
				LEFT OUTER JOIN ( 
					SELECT A.BOX_CODE
							, B.SCAN_CODE
							, A.IPSU_QTY
						FROM CD_BOX_MST AS A
						INNER JOIN CD_PRODUCT_CMN AS B ON A.ITM_CODE = B.ITM_CODE
				) AS G ON B.ITM_CODE = G.BOX_CODE

			   WHERE A.REPORT_DATE = @P_REPORT_DATE
			     --AND B.ITM_GB = '1'
			     AND 1=(CASE WHEN @P_LOT_OIL_GB = '' THEN 1 WHEN @P_LOT_OIL_GB != '' AND B.LOT_OIL_GB = @P_LOT_OIL_GB THEN 1 ELSE 2 END)
				 AND 1=(CASE WHEN @P_LOT_PARTNER_GB = '' THEN 1 WHEN @P_LOT_PARTNER_GB != '' AND B.LOT_PARTNER_GB = @P_LOT_PARTNER_GB THEN 1 ELSE 2 END)
				 
		END

	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
	
END

GO

