/*
-- 생성자 :	강세미
-- 등록일 :	2023.01.24
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 박스 마스터 리스트 출력
-- 실행문 : 
EXEC PR_BOX_MST_LIST '','','',''
*/
CREATE PROCEDURE [dbo].[PR_BOX_MST_LIST]
( 
	@P_SCAN_CODE	NVARCHAR(14) = '',   -- 상품코드
	@P_VEN_CODE		NVARCHAR(7) = '',		-- 거래처코드
	@P_LRG_CODE		NVARCHAR(2) = '',		-- 대분류코드
	@P_MID_CODE		NVARCHAR(4) = ''		-- 중분류코드
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	SET @P_SCAN_CODE = ISNULL(@P_SCAN_CODE, '')
	SET @P_VEN_CODE = ISNULL(@P_VEN_CODE, '')
	SET @P_LRG_CODE = ISNULL(@P_LRG_CODE, '')
	SET @P_MID_CODE = ISNULL(@P_MID_CODE, '')
	
	BEGIN TRY 
		SELECT ROW_NUMBER() OVER(ORDER BY BOX_CODE) AS ROW_NUM
			  , A.BOX_CODE
			  , PD_BOX.SCAN_CODE AS BOX_SCAN_CODE
			  , PD_BOX.ITM_NAME_DETAIL AS BOX_NAME
			  , A.ITM_CODE
			  , PD_ITM.SCAN_CODE AS SCAN_CODE
			  , PD_ITM.ITM_NAME_DETAIL AS ITM_NAME
			  , A.IPSU_QTY
		  FROM CD_BOX_MST AS A
				INNER JOIN CD_PRODUCT_CMN AS PD_BOX -- 박스상품
					ON PD_BOX.ITM_CODE = A.BOX_CODE
				INNER JOIN CD_PRODUCT_CMN AS PD_ITM -- 단품상품
					ON PD_ITM.ITM_CODE = A.ITM_CODE
				INNER JOIN CD_MID_MST AS D
					ON D.MID_CODE = PD_BOX.MID_CODE
				INNER JOIN CD_LRG_MST AS E
					ON E.LRG_CODE = D.LRG_CODE
				INNER JOIN CD_MID_MST AS F
					ON F.MID_CODE = PD_ITM.MID_CODE
				INNER JOIN CD_LRG_MST AS G
					ON G.LRG_CODE = F.LRG_CODE 
			--WHERE (B.SCAN_CODE = (CASE WHEN @P_SCAN_CODE <> '' THEN @P_SCAN_CODE ELSE B.SCAN_CODE END)
			--		OR C.SCAN_CODE = (CASE WHEN @P_SCAN_CODE <> '' THEN @P_SCAN_CODE ELSE C.SCAN_CODE END))
			--	 AND ISNULL(B.VEN_CODE,'') = (CASE WHEN @P_VEN_CODE <> '' THEN @P_VEN_CODE ELSE ISNULL(B.VEN_CODE,'') END)
			--	 AND (E.LRG_CODE = (CASE WHEN @P_LRG_CODE <> '' THEN @P_LRG_CODE ELSE E.LRG_CODE END) AND D.MID_CODE = (CASE WHEN @P_MID_CODE <> '' THEN @P_MID_CODE ELSE D.MID_CODE END) 
			--		OR	G.LRG_CODE = (CASE WHEN @P_LRG_CODE <> '' THEN @P_LRG_CODE ELSE G.LRG_CODE END) AND F.MID_CODE = (CASE WHEN @P_MID_CODE <> '' THEN @P_MID_CODE ELSE F.MID_CODE END)) 
			WHERE  (PD_BOX.SCAN_CODE = (CASE WHEN @P_SCAN_CODE <> '' THEN @P_SCAN_CODE ELSE PD_BOX.SCAN_CODE END)
					AND ( ISNULL(PD_BOX.VEN_CODE,'') = (CASE WHEN @P_VEN_CODE <> '' THEN @P_VEN_CODE ELSE ISNULL(PD_BOX.VEN_CODE,'') END)
					OR ISNULL(PD_BOX.VEN_CODE_2,'') = (CASE WHEN @P_VEN_CODE <> '' THEN @P_VEN_CODE ELSE ISNULL(PD_BOX.VEN_CODE_2,'') END)
					OR ISNULL(PD_BOX.VEN_CODE_3,'') = (CASE WHEN @P_VEN_CODE <> '' THEN @P_VEN_CODE ELSE ISNULL(PD_BOX.VEN_CODE_3,'') END)
					OR ISNULL(PD_BOX.VEN_CODE_4,'') = (CASE WHEN @P_VEN_CODE <> '' THEN @P_VEN_CODE ELSE ISNULL(PD_BOX.VEN_CODE_4,'') END)
					OR ISNULL(PD_BOX.VEN_CODE_5,'') = (CASE WHEN @P_VEN_CODE <> '' THEN @P_VEN_CODE ELSE ISNULL(PD_BOX.VEN_CODE_5,'') END))
					AND (E.LRG_CODE = (CASE WHEN @P_LRG_CODE <> '' THEN @P_LRG_CODE ELSE E.LRG_CODE END) AND D.MID_CODE = (CASE WHEN @P_MID_CODE <> '' THEN @P_MID_CODE ELSE D.MID_CODE END) 
					))
					OR 
					(PD_ITM.SCAN_CODE = (CASE WHEN @P_SCAN_CODE <> '' THEN @P_SCAN_CODE ELSE PD_ITM.SCAN_CODE END)
					AND ( ISNULL(PD_ITM.VEN_CODE,'') = (CASE WHEN @P_VEN_CODE <> '' THEN @P_VEN_CODE ELSE ISNULL(PD_ITM.VEN_CODE,'') END)
					OR ISNULL(PD_ITM.VEN_CODE_2,'') = (CASE WHEN @P_VEN_CODE <> '' THEN @P_VEN_CODE ELSE ISNULL(PD_ITM.VEN_CODE_2,'') END)
					OR ISNULL(PD_ITM.VEN_CODE_3,'') = (CASE WHEN @P_VEN_CODE <> '' THEN @P_VEN_CODE ELSE ISNULL(PD_ITM.VEN_CODE_3,'') END)
					OR ISNULL(PD_ITM.VEN_CODE_4,'') = (CASE WHEN @P_VEN_CODE <> '' THEN @P_VEN_CODE ELSE ISNULL(PD_ITM.VEN_CODE_4,'') END)
					OR ISNULL(PD_ITM.VEN_CODE_5,'') = (CASE WHEN @P_VEN_CODE <> '' THEN @P_VEN_CODE ELSE ISNULL(PD_ITM.VEN_CODE_5,'') END))
					AND (G.LRG_CODE = (CASE WHEN @P_LRG_CODE <> '' THEN @P_LRG_CODE ELSE G.LRG_CODE END) AND F.MID_CODE = (CASE WHEN @P_MID_CODE <> '' THEN @P_MID_CODE ELSE F.MID_CODE END) 
					))


	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
	
END

GO

