/*
-- 생성자	:	최수민
-- 등록일	:	2023.10.08
-- 설 명	:	더존 광리항목 조회
-- 실행문	: 
EXEC PR_DOUZONE_MGMT_ITEM_LIST ''
*/
CREATE PROCEDURE [dbo].[PR_DOUZONE_MGMT_ITEM_LIST]
( 
	@P_SCAN_CODE		NVARCHAR(14) = ''		-- 스캔코드
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
 
	BEGIN TRY 
		
		SELECT CMN.SCAN_CODE
			 , CMN.ITM_NAME
			 , DZ.MGMT_ENTRY_1
			 , CD1.CD_NM AS MGMT_ENTRY_1_NM
			 , DZ.MGMT_ENTRY_2
			 , CD2.CD_NM AS MGMT_ENTRY_2_NM
			 , DZ.MGMT_ENTRY_3
			 , CD3.CD_NM AS MGMT_ENTRY_3_NM
		  FROM CD_PRODUCT_CMN AS CMN
		  LEFT OUTER JOIN TBL_DOUZONE_MGMT_ITEM AS DZ ON CMN.SCAN_CODE = DZ.SCAN_CODE
		  LEFT OUTER JOIN TBL_COMM_CD_MST AS CD1 ON CD1.CD_CL = 'DOUZONE_D93' AND DZ.MGMT_ENTRY_1 = CD1.CD_ID	--원재료 구분
		  LEFT OUTER JOIN TBL_COMM_CD_MST AS CD2 ON CD2.CD_CL = 'DOUZONE_D95' AND DZ.MGMT_ENTRY_2 = CD2.CD_ID	--저장품 구분
		  LEFT OUTER JOIN TBL_COMM_CD_MST AS CD3 ON CD3.CD_CL = 'DOUZONE_D96' AND DZ.MGMT_ENTRY_3 = CD3.CD_ID	--제품매출 구분
		 WHERE CMN.SCAN_CODE = CASE WHEN @P_SCAN_CODE <> '' THEN @P_SCAN_CODE ELSE CMN.SCAN_CODE END
		 ORDER BY CMN.SCAN_CODE

	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
	
END

GO

