/*
-- 생성자 :	강세미
-- 등록일 :	2023.04.17
-- 설 명  : 출고서류관리 > 파일 리스트 조회
-- 수정자 :
-- 수정일 :
-- 설 명  :	
-- 실행문 : 
EXEC PR_FILE_LIST '2240416010'
*/
CREATE PROCEDURE [dbo].[PR_FILE_LIST]
( 
	@P_ORD_NO		NVARCHAR(11) = ''			-- 주문번호
)
AS
BEGIN

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
 
	BEGIN TRY 
	 
		SELECT 
			ROW_NUMBER() OVER(ORDER BY A.SEQ ASC) AS ROW_NUM,
			A.SEQ,
			A.ORD_NO,
			A.DOC_NAME,
			A.REAL_DOC_NAME,
			A.REMARKS,
			CONVERT(NVARCHAR(8), A.IDATE, 112)AS IDATE,
			A.IEMP_ID,
			B.USER_NM AS IEMP_NM,
			CONVERT(NVARCHAR(8), A.UDATE, 112)AS UDATE,
			A.UEMP_ID,
			C.USER_NM AS UEMP_NM
			FROM PO_DOCUMENT_REQ AS A
			INNER JOIN TBL_USER_MST AS B ON A.IEMP_ID = B.[USER_ID]
			LEFT OUTER JOIN TBL_USER_MST AS C ON A.UEMP_ID = C.[USER_ID]
		WHERE ORD_NO = @P_ORD_NO
					
	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
	
END

GO

