/*
-- 생성자 :	강세미
-- 등록일 :	2024.05.17
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 수입발주등록 DTL 조회
-- 실행문 : 
EXEC PR_IM_ORDER_DTL_LIST 'PO240510'
*/
CREATE PROCEDURE [dbo].[PR_IM_ORDER_DTL_LIST]
( 
	@P_PO_NO	NVARCHAR(15) = ''   -- PO번호
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
 
	BEGIN TRY 
		SELECT ROW_NUMBER() OVER(ORDER BY A.SEQ) AS ROW_NUM,
			   A.PO_NO,
			   A.SEQ,
			   A.ITM_CODE,
			   A.ORD_QTY,
			   A.FRGN_WPRC,
			   A.FRGN_WPRC_AMT,
			   A.WPRC,
			   A.WPRC_AMT,
			   A.TAX_GB,
			   A.ORG_CODE,
			   A.PUR_WPRC,
			   A.PUR_WAMT,
			   B.ITM_NAME,
			   B.UNIT_CAPACITY,
			   C.CD_NM AS TAX_GB_NM,
			   D.CD_NM AS ORG_NM,
			   E.CD_NM AS UNIT_NM
		  FROM IM_ORDER_DTL A
			INNER JOIN CD_PRODUCT_CMN B ON A.ITM_CODE = B.ITM_CODE
			LEFT OUTER JOIN TBL_COMM_CD_MST C ON C.CD_CL = 'TAX_GB' AND C.CD_ID = A.TAX_GB
			LEFT OUTER JOIN TBL_COMM_CD_MST D ON D.CD_CL = 'IM_ORG_CODE' AND D.CD_ID = A.ORG_CODE
			LEFT OUTER JOIN TBL_COMM_CD_MST E ON E.CD_CL = 'UNIT' AND E.CD_ID = B.UNIT
		 WHERE A.PO_NO = @P_PO_NO

	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
	
END

GO

