/*
-- 생성자 :	윤현빈
-- 등록일 :	2024.11.07
-- 설 명  : 일보제품정렬관리 조회
-- 실행문 : EXEC PR_ITM_SORT_LIST '','';
*/
CREATE PROCEDURE [dbo].[PR_ITM_SORT_LIST]
	@P_APP_DATE			NVARCHAR(8),	-- 조회일자
	@P_ITM_CATEGORY		NVARCHAR(2),	-- 카테고리
	@P_TAB_INDEX		INT	-- 탭 인덱스
AS 
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	BEGIN TRY 

		SELECT ROW_NUMBER() OVER(ORDER BY C.CD_ID, A.SORT_ORDER, A.SORT_ORDER) AS ROW_NUM
		     , C.CD_ID AS ITM_CATEGORY
			 , A.SORT_ORDER
			 , A.SCAN_CODE
			 , B.ITM_NAME
			 , A.START_DATE
			 , A.END_DATE
			FROM RP_ITM_SORT AS A
			LEFT OUTER JOIN CD_PRODUCT_CMN AS B ON A.SCAN_CODE = B.SCAN_CODE
			LEFT OUTER JOIN TBL_COMM_CD_MST AS C ON C.CD_CL = 'ITM_CATEGORY' AND A.ITM_CATEGORY = C.CD_ID
		   WHERE @P_APP_DATE BETWEEN A.START_DATE AND A.END_DATE
		     AND 1=(CASE WHEN @P_ITM_CATEGORY = '' THEN 1 WHEN @P_ITM_CATEGORY != '' AND A.ITM_CATEGORY = @P_ITM_CATEGORY THEN 1 ELSE 2 END)
			 AND A.PARTNER_GB = @P_TAB_INDEX
		;
	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
	
END

GO

