
/*
-- 생성자 :	최수민
-- 등록일 :	2024.08.12
-- 설 명  : 
			앱(API) SET 관련 메뉴 3개 조회
			A. 생산자재등록 상세 목록 조회
			B. SET생산등록 상세 목록 조회
			C. 자재환원등록 상세 목록 조회
-- 수정자 : 
-- 수정일 : 2024.12.05 임현태 - CFM_FLAG 조회
			2024.12.12 임현태 - A,C 메뉴 SEQ 컬럼 조회 추가
								A,C 메뉴 RESTORE_YN 컬럼 조회에서 삭제
-- 실행문 : 
EXEC PR_MO_SET_DTL_LIST 'SET20240807', '20240813', 'A'
*/
CREATE PROCEDURE [dbo].[PR_MO_SET_DTL_LIST]
( 
	@P_SET_PLAN_ID		NVARCHAR(11) = '',		-- 작업번호
	@P_PROD_DT			NVARCHAR(8) = '',		-- 생산일자
	@P_MENU_GUBUN		NVARCHAR(1) = ''		-- 메뉴구분
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	BEGIN TRY 

		IF @P_MENU_GUBUN = 'A'
		BEGIN

			SELECT COMP.SET_PLAN_ID
				 , COMP.SEQ
				 , COMP.PROD_DT
				 , COMP.SET_COMP_CD
				 , CMN.ITM_NAME
				 , COMP.LOT_NO
				 , COMP.COMP_QTY
				 , 0 AS PROD_QTY
				 , NULL AS SCAN_CODE
				 , COMP.COMP_CFM_FLAG AS CFM_FLAG
			  FROM PD_SET_RESULT_COMP AS COMP
			 INNER JOIN CD_PRODUCT_CMN AS CMN ON COMP.SET_COMP_CD = CMN.SCAN_CODE
			 WHERE COMP.SET_PLAN_ID = @P_SET_PLAN_ID
			   AND COMP.PROD_DT = @P_PROD_DT
			   AND COMP.RESTORE_YN = 'N'
			   AND CMN.ITM_GB = '1'
		END
		ELSE
		IF @P_MENU_GUBUN = 'B'
		BEGIN

			SELECT PROD.SET_PLAN_ID
				 , NULL AS SEQ 
				 , PROD.PROD_DT
				 , PROD.SCAN_CODE
				 , CMN.ITM_NAME
				 , PROD.PROD_QTY
				 , NULL AS SET_COMP_CD
				 , NULL AS LOT_NO
				 , 0 AS COMP_QTY
				 , PROD.PROD_CFM_FLAG AS CFM_FLAG
			  FROM PD_SET_RESULT_PROD AS PROD
			 INNER JOIN CD_PRODUCT_CMN AS CMN ON PROD.SCAN_CODE = CMN.SCAN_CODE
			 WHERE PROD.SET_PLAN_ID = @P_SET_PLAN_ID
			   AND PROD.PROD_DT = @P_PROD_DT
		END
		ELSE
		IF @P_MENU_GUBUN = 'C'
		BEGIN

			SELECT COMP.SET_PLAN_ID
				 , COMP.SEQ
				 , COMP.PROD_DT
				 , COMP.SET_COMP_CD
				 , CMN.ITM_NAME
				 , COMP.LOT_NO
				 , COMP.COMP_QTY
				 , 0 AS PROD_QTY
				 , NULL AS SCAN_CODE
				 , COMP.COMP_CFM_FLAG AS CFM_FLAG 
			  FROM PD_SET_RESULT_COMP AS COMP
			 INNER JOIN CD_PRODUCT_CMN AS CMN ON COMP.SET_COMP_CD = CMN.SCAN_CODE
			 WHERE COMP.SET_PLAN_ID = @P_SET_PLAN_ID
			   AND COMP.PROD_DT = @P_PROD_DT
			   AND COMP.RESTORE_YN = 'Y'
		END

					
	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
	
END

GO

