/*
-- 생성자 :	강세미
-- 등록일 :	2024.01.15
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 마이메뉴 저장
-- 실행문 : EXEC PR_MY_MENU_PUT '020101','I'
*/
CREATE PROCEDURE [dbo].[PR_MY_MENU_PUT]
	@P_USER_ID NVARCHAR(20), 				-- 사용자ID
	@P_MENU_CODE NVARCHAR(100), 			-- 메뉴코드
	@P_MODE NVARCHAR(1)						-- I: 등록 D: 삭제
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	DECLARE @RETURN_CODE INT = 0			-- 리턴코드
	DECLARE @RETURN_MESSAGE NVARCHAR(10) = ''		-- 리턴메시지

	DECLARE @MENU_LINK		NVARCHAR(150)	-- 메뉴경로
	DECLARE @MENU_NM		NVARCHAR(100)	-- 메뉴명

	BEGIN TRY 

		IF (@P_MODE = 'I')
			BEGIN
				IF NOT EXISTS(SELECT 1 FROM TBL_MY_MENU WHERE USER_ID = @P_USER_ID AND MENU_CODE = @P_MENU_CODE)
				BEGIN
					INSERT INTO TBL_MY_MENU(
									USER_ID,
									MENU_CODE,
									IDATE
									) VALUES (
									@P_USER_ID,
									@P_MENU_CODE,
									GETDATE()
									)
				END
			END
		ELSE
			BEGIN
				DELETE TBL_MY_MENU
				 WHERE USER_ID = @P_USER_ID
					AND MENU_CODE = @P_MENU_CODE
			END

		SELECT @MENU_LINK = MENU_LINK,
			   @MENU_NM = MENU_NM
		  FROM TBL_MENU_INFO
		 WHERE MENU_CODE = @P_MENU_CODE

		SET @RETURN_CODE = 0 -- 저장완료
		SET @RETURN_MESSAGE = DBO.GET_ERR_MSG('0')

	END TRY
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	

		SET @RETURN_CODE = -1 -- 저장 실패
		SET @RETURN_MESSAGE = DBO.GET_ERR_MSG('-1')
	END CATCH
	
	
	SELECT @RETURN_CODE AS RETURN_CODE, @RETURN_MESSAGE AS RETURN_MESSAGE, @P_MENU_CODE AS MENU_CODE, @MENU_LINK AS MENU_LINK, @MENU_NM AS MENU_NM
END

GO

