/*
-- 생성자 :	강세미
-- 등록일 :	2024.01.15
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 마이메뉴 여부 체크
-- 실행문 : EXEC PR_MY_MENU_CHECK 'admin', '020101'
*/
CREATE PROCEDURE [dbo].[PR_MY_MENU_CHECK]
	@P_USER_ID NVARCHAR(20), 				-- 사용자ID
	@P_MENU_CODE NVARCHAR(100) 			-- 메뉴코드
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	DECLARE @RETURN_CODE INT = 0			-- 리턴코드
	DECLARE @RETURN_MESSAGE NVARCHAR(10) = ''		-- 리턴메시지

	BEGIN TRY 

		SELECT @RETURN_CODE = (CASE WHEN COUNT(1) > 0 THEN 0 ELSE -1 END)
		  FROM TBL_MY_MENU
		 WHERE USER_ID = @P_USER_ID
			AND MENU_CODE = @P_MENU_CODE
		
	END TRY
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	

		SET @RETURN_CODE = 9
		SET @RETURN_MESSAGE = '조회 실패하였습니다.'
	END CATCH
	
	
	SELECT @RETURN_CODE AS RETURN_CODE, @RETURN_MESSAGE AS RETURN_MESSAGE
END

GO

