/*
-- 생성자 :	윤현빈
-- 등록일 :	2024.10.21
-- 수정일 : - 
-- 설 명  : 주문등록 DTL 조회 (무자료)
-- 실행문 : PR_ORDER_DTL_LIST_FOR_NO_DOC ''
*/
CREATE PROCEDURE [dbo].[PR_ORDER_DTL_LIST_FOR_NO_DOC]
( 
	@P_ORD_NO	NVARCHAR(11) = ''   -- 주문번호
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
 
	BEGIN TRY 
		SELECT ROW_NUMBER() OVER(ORDER BY SEQ) AS ROW_NUM
			 , A.SCAN_CODE
			 , B.ITM_NAME
			 , C.CD_NM AS TAX_GB
			 , ISNULL(A.ORD_QTY, 0) AS ORD_QTY
			 , ISNULL(A.PICKING_QTY, 0) AS ORG_PICKING_QTY
			 , 0.00 AS PICKING_QTY
			 , ISNULL(ROUND(A.ORD_SPRC, 0), 0) AS ORD_SPRC
			 , ISNULL(ROUND(A.ORD_SVAT, 0), 0) AS ORD_SVAT
			 , ISNULL(A.ORD_SPRC, 0) + ISNULL(A.ORD_SVAT, 0) AS ORD_AMT
			 , ISNULL(A.ORD_SAMT, 0) AS ORD_SAMT
             , ISNULL(ROUND(A.PICKING_SPRC, 0), 0) AS PICKING_SPRC
             , ISNULL(ROUND(A.PICKING_SVAT, 0), 0) AS PICKING_SVAT
             , ISNULL(A.PICKING_SPRC, 0) + ISNULL(A.PICKING_SVAT, 0) AS PICKING_AMT
             , ISNULL(A.PICKING_SAMT, 0) AS PICKING_SAMT
		  FROM PO_ORDER_DTL AS A
		  INNER JOIN CD_PRODUCT_CMN AS B ON B.SCAN_CODE = A.SCAN_CODE
		  LEFT OUTER JOIN TBL_COMM_CD_MST AS C ON A.TAX_GB = C.CD_ID AND C.CD_CL = 'TAX_GB'
		 WHERE A.ORD_NO = @P_ORD_NO

	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
	
END

GO

