/*
-- 생성자 :	강세미
-- 등록일 :	2023.01.17
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 거래처 배송지 리스트 출력
-- 실행문 : 
EXEC PR_PARTNER_DELIVERY_LIST 'UM20126'
EXEC PR_PARTNER_DELIVERY_LIST 'UM10026'
*/
CREATE PROCEDURE [dbo].[PR_PARTNER_DELIVERY_LIST]
( 
	@P_VEN_CODE		NVARCHAR(7) = ''	-- 거래처명(코드)
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	SET @P_VEN_CODE = ISNULL(@P_VEN_CODE, '')
	 
	BEGIN TRY 
	EXEC UMAC_CERT_OPEN_KEY; -- OPEN
		IF dbo.FN_PARTNER_DELIVERY_TREE_JSON('', NULL, 0, @P_VEN_CODE) IS NULL
			BEGIN
				SELECT '-1' AS RETURN_JSON
			END
		ELSE 
			BEGIN
				SELECT dbo.FN_PARTNER_DELIVERY_TREE_JSON('', NULL, 0, @P_VEN_CODE) AS RETURN_JSON;
			END
	EXEC UMAC_CERT_CLOSE_KEY -- CLOSE
	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
	
END

GO

