/*
-- 생성자 :	윤현빈
-- 등록일 :	2024.06.19
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 입듬등록, 삭제예정
-- 실행문 : EXEC PR_PARTNER_DEPOSIT_DTL_PUT 'UM20127', '02', '20240618', 200, '', 'testy'
*/
CREATE PROCEDURE [dbo].[PR_PARTNER_DEPOSIT_DTL_PUT]

	--@P_VEN_CODE		NVARCHAR(7) = '',	-- 거래처코드
	--@P_DEPOSIT_GB	NVARCHAR(2) = '',	-- 결제수단
	--@P_DEPOSIT_DT	NVARCHAR(8) = '',	-- 입금일자
	--@P_DEPOSIT_AMT	INT,				-- 입금액
	--@P_DEPOSIT_NO	NVARCHAR(11),		-- 입금번호
	--@P_EMP_ID		NVARCHAR(20),		-- 등록자
	--@P_MODE			NVARCHAR(1)			-- I: 등록 U: 수정 D: 삭제
	
	
	@P_JSONDT		VARCHAR(8000) = '',
	@P_EMP_ID		VARCHAR(20)				-- 아이디
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	DECLARE @RETURN_CODE 	INT 			= 0		-- 리턴코드
	DECLARE @RETURN_MESSAGE NVARCHAR(10) 	= '' 	-- 리턴메시지
	--DECLARE @IDATE VARCHAR(8) = CONVERT(VARCHAR(8), GETDATE(), 112)
	--DECLARE @DEPOSIT_NO_CNT INT, @DEPOSIT_NO NVARCHAR(11)
	--DECLARE @R_MOID NVARCHAR(100)

	BEGIN TRAN
	BEGIN TRY
	
	print(@P_JSONDT);


		DECLARE CS_DEPOSIT CURSOR FOR
		
		SELECT VEN_CODE, DEPOSIT_GB, DEPOSIT_DT, DEPOSIT_AMT, DEPOSIT_NO, MODE FROM 
			OPENJSON ( @P_JSONDT )   
				WITH (    
					  VEN_CODE	NVARCHAR(7) '$.VEN_CODE'
					, DEPOSIT_GB	NVARCHAR(2) '$.DEPOSIT_GB'
					, DEPOSIT_DT	NVARCHAR(8) '$.DEPOSIT_DT'
					, DEPOSIT_AMT	INT '$.DEPOSIT_AMT'
					, DEPOSIT_NO	NVARCHAR(11) '$.DEPOSIT_NO'
					, MODE		NVARCHAR(1) '$.MODE'
				)

		OPEN CS_DEPOSIT

		DECLARE @VEN_CODE		NVARCHAR(7)
			  , @DEPOSIT_GB		NVARCHAR(2)
			  , @DEPOSIT_DT		NVARCHAR(8)
			  , @DEPOSIT_AMT	INT
			  , @DEPOSIT_NO		NVARCHAR(11)
			  , @MODE			NVARCHAR(1)

		FETCH NEXT FROM CS_DEPOSIT INTO @VEN_CODE, @DEPOSIT_GB, @DEPOSIT_DT, @DEPOSIT_AMT, @DEPOSIT_NO, @MODE

		WHILE(@@FETCH_STATUS=0)

		BEGIN

			print(concat('시작 : ', @VEN_CODE, @DEPOSIT_GB, @DEPOSIT_DT, @DEPOSIT_AMT, @DEPOSIT_NO, @MODE));
			
			FETCH NEXT FROM CS_DEPOSIT INTO @VEN_CODE, @DEPOSIT_GB, @DEPOSIT_DT, @DEPOSIT_AMT, @DEPOSIT_NO, @MODE
		END

		CLOSE CS_DEPOSIT
		DEALLOCATE CS_DEPOSIT


		-- Q 입금등록 시 미수남은 주문서 찾아서 PA_ACCT_DEPOSIT_ORD에도 넣어줘야는건가?
		-- => 전체적으로 수정해야함

		--EXEC PR_ACCT_ORDER_RETURN_ID @R_MOID OUT

		----# 일자별 입금번호 순번 생성
		--SELECT @DEPOSIT_NO_CNT = COUNT(MOID) + 1 FROM PA_ACCT_DEPOSIT WHERE DEPOSIT_DT = @IDATE

		--IF @DEPOSIT_NO_CNT < 10
		--BEGIN
		--	SET @DEPOSIT_NO = @IDATE + '00' + CONVERT(VARCHAR, @DEPOSIT_NO_CNT)
		--END
		--ELSE IF @DEPOSIT_NO_CNT > 9 AND @DEPOSIT_NO_CNT < 100
		--	SET @DEPOSIT_NO = @IDATE + '0' + CAST(@DEPOSIT_NO_CNT AS VARCHAR)
		--ELSE 
		--	SET @DEPOSIT_NO = @IDATE + CAST(@DEPOSIT_NO_CNT AS VARCHAR)

		--IF @P_MODE = 'D'
		--BEGIN
		--	DELETE FROM PA_ACCT_DEPOSIT
		--	   WHERE DEPOSIT_NO = @P_DEPOSIT_NO
		--	;
		--END
		--ELSE
		--BEGIN
		--	MERGE INTO PA_ACCT_DEPOSIT AS A
		--		USING (SELECT 1 AS dual) AS B
		--		ON (A.DEPOSIT_NO = @P_DEPOSIT_NO)
		--	WHEN MATCHED THEN
		--		UPDATE SET A.DEPOSIT_GB = @P_DEPOSIT_GB
		--				 , A.DEPOSIT_AMT = @P_DEPOSIT_AMT
		--				 , A.DEPOSIT_DT = @P_DEPOSIT_DT
		--				 , A.UDATE = GETDATE()
		--				 , A.UEMP_ID = @P_EMP_ID
		--	WHEN NOT MATCHED THEN
		--		INSERT
		--		(
		--			MOID
		--		  , VEN_CODE
		--		  , DEPOSIT_GB
		--		  , DEPOSIT_NO
		--		  , DEPOSIT_AMT
		--		  , DEPOSIT_DT
		--		  , DEPOSIT_FISH
		--		  , IDATE
		--		  , IEMP_ID
		--		) 
		--		VALUES
		--		(
		--			@R_MOID
		--		  , @P_VEN_CODE
		--		  , @P_DEPOSIT_GB
		--		  , @DEPOSIT_NO
		--		  , @P_DEPOSIT_AMT
		--		  , @P_DEPOSIT_DT
		--		  , 'Y'
		--		  , GETDATE()
		--		  , @P_EMP_ID
		--		)
		--		;
		--END

		SET @RETURN_CODE = 0 -- 저장완료
		SET @RETURN_MESSAGE = DBO.GET_ERR_MSG('0')
		

		COMMIT;

	END TRY
	BEGIN CATCH		
	
		IF @@TRANCOUNT > 0
		BEGIN
			
			ROLLBACK TRAN

			--에러 로그 테이블 저장
			INSERT INTO TBL_ERROR_LOG 
			SELECT ERROR_PROCEDURE()	-- 프로시저명
			, ERROR_MESSAGE()			-- 에러메시지
			, ERROR_LINE()				-- 에러라인
			, GETDATE();
		
			SET @RETURN_CODE = -1; -- 저장 실패
			SET @RETURN_MESSAGE = DBO.GET_ERR_MSG('-1');
	
		END
			
	END CATCH

	SELECT @RETURN_CODE AS RETURN_CODE, @RETURN_MESSAGE AS RETURN_MESSAGE
END

GO

