/*
-- 생성자 :	강세미
-- 등록일 :	2024.01.09
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 권한그룹 별 기본메뉴 저장
-- 실행문 : EXEC PR_ROLE_MENU_PUT 'ROLE01','010101','메뉴명','admin'
*/
CREATE PROCEDURE [dbo].[PR_ROLE_MENU_PUT]
	@P_ROLE_ID NVARCHAR(6),					-- 권한그룹코드
	@P_MENU_CODE NVARCHAR(100), 			-- 메뉴코드
	@P_EMP_ID NVARCHAR(20) 					-- 아이디
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	DECLARE @RETURN_CODE INT = 0			-- 리턴코드
	DECLARE @RETURN_MESSAGE NVARCHAR(10) = ''		-- 리턴메시지

	DECLARE @MAX INT = 0
	DECLARE @COUNT INT = 0
	DECLARE @USER_ID NVARCHAR(20)

	BEGIN TRY 
		INSERT INTO TBL_ROLE_MENU(
						ROLE_ID,
						MENU_CODE,
						IDATE,
						IEMP_ID
						) VALUES (
						@P_ROLE_ID,
						@P_MENU_CODE,
						GETDATE(),
						@P_EMP_ID
						)

		-- 기본 권한 메뉴 추가 시 사용자별 권한에도 INSERT(시스템 관리자만)
		IF @P_ROLE_ID = 'ROLE01'
			BEGIN 
				INSERT INTO TBL_USER_ROLE_MST(USER_ID, MENU_CODE, IDATE, IEMP_ID)
				SELECT A.USER_ID, @P_MENU_CODE, GETDATE(), @P_EMP_ID 
				FROM TBL_USER_MST AS A
				LEFT JOIN TBL_USER_ROLE_MST AS B
					 ON A.USER_ID = B.USER_ID AND B.MENU_CODE = @P_MENU_CODE
				WHERE A.ROLE_ID = 'ROLE01' AND B.USER_ID IS NULL;
			END

		SET @RETURN_CODE = 0 -- 저장완료
		SET @RETURN_MESSAGE = DBO.GET_ERR_MSG('0')

	END TRY
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	

		SET @RETURN_CODE = -1 -- 저장실패
		SET @RETURN_MESSAGE = DBO.GET_ERR_MSG('-1')
	END CATCH
	
	
	SELECT @RETURN_CODE AS RETURN_CODE, @RETURN_MESSAGE AS RETURN_MESSAGE
END

GO

