/*
-- 생성자 :	강세미
-- 등록일 :	2023.01.09
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 권한그룹 별 메뉴 출력
-- 실행문 : 
EXEC PR_ROLE_MENU_LIST 'ROLE01'
*/
CREATE PROCEDURE [dbo].[PR_ROLE_MENU_LIST]
( @P_ROLE_ID NVARCHAR(6) = '' -- 권한그룹코드
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
 
	BEGIN TRY 
		SELECT ROW_NUMBER() OVER(ORDER BY A.MENU_CODE) AS ROW_NUM
			  , ROLE_ID
			  , A.MENU_CODE
			  , B.MENU_NM
			  , 'Y' AS USE_YN	 
		  FROM TBL_ROLE_MENU AS A
			INNER JOIN TBL_MENU_INFO AS B
			ON B.MENU_CODE = A.MENU_CODE
		 WHERE ROLE_ID = @P_ROLE_ID
		 UNION ALL
		SELECT ROW_NUMBER() OVER(ORDER BY A.MENU_CODE) AS ROW_NUM
			  , @P_ROLE_ID
			  , A.MENU_CODE
			  , A.MENU_NM
			  , 'N' AS USE_YN
		  FROM TBL_MENU_INFO AS A
		 WHERE A.MENU_CODE NOT IN 
				(SELECT MENU_CODE
					FROM TBL_ROLE_MENU
				  WHERE ROLE_ID = @P_ROLE_ID)
			AND A.MENU_LINK != ''
			AND A.DEL_YN = 'N'
	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
	
END

GO

