/*
-- 생성자 :	윤현빈
-- 등록일 :	2024.07.05
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 재고조사 ID 조회
-- 실행문 : EXEC PR_STOCK_SURVEY_ID_LIST  ''
*/
CREATE PROCEDURE [dbo].[PR_STOCK_SURVEY_ID_LIST]
( 
	@P_YYYYMM	NVARCHAR(6) = ''	-- YYYYMM
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	BEGIN TRY 	
		SELECT A.INV_DT
		     , A.SURVEY_ID
			 , A.SURVEY_GB
			 , B.CD_NM AS SURVEY_GB_NM
			 , A.CFM_FLAG
			FROM IV_SCHEDULER AS A
			INNER JOIN TBL_COMM_CD_MST AS B ON B.CD_CL = 'INV_SURVEY_GB' AND A.SURVEY_GB = B.CD_ID
		   WHERE INV_DT LIKE @P_YYYYMM + '%'
		   ORDER BY SURVEY_ID DESC

	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
	
END

GO

