/*
-- 생성자 :	윤현빈
-- 등록일 :	2024.05.28
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 재고이력현황
-- 실행문 : EXEC PR_STOCK_HISTORY_LIST '','','','',''
*/
CREATE PROCEDURE [dbo].[PR_STOCK_HISTORY_LIST]
( 
	@P_SCAN_CODE	NVARCHAR(14) = '',	-- 상품코드
	@P_FROM_DT		NVARCHAR(8) = '',	-- 상품코드
	@P_TO_DT		NVARCHAR(8) = '',	-- 상품코드
	@P_LRG_CODE	 	NVARCHAR(2) = '',	-- 대분류 코드
	@P_MID_CODE	 	NVARCHAR(4) = ''	-- 중분류 코드
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	BEGIN TRY 	
		

		SELECT B.SCAN_CODE
			 , B.ITM_NAME
			 , B.WEIGHT_GB
			 , A.INV_DT
			 , A.BASE_INV_QTY
			 , A.PUR_QTY
			 , A.PROD_QTY
			 , A.RTN_QTY
			 , A.SALE_QTY
			 , A.INV_ADJ_QTY
			 , A.INV_END_QTY
			FROM IV_DT_ITEM_COLL AS A
			INNER JOIN CD_PRODUCT_CMN AS B ON A.ITM_CODE = B.ITM_CODE
			INNER JOIN CD_MID_MST AS MID ON B.MID_CODE = MID.MID_CODE 
			INNER JOIN CD_LRG_MST AS LRG ON MID.LRG_CODE = LRG.LRG_CODE 
		   WHERE A.INV_DT BETWEEN @P_FROM_DT AND @P_TO_DT
		     AND 1=(CASE WHEN @P_SCAN_CODE = '' THEN 1 WHEN @P_SCAN_CODE != '' AND B.SCAN_CODE = @P_SCAN_CODE THEN 1 ELSE 2 END)
		     AND 1=(CASE WHEN @P_LRG_CODE = '' THEN 1 WHEN @P_LRG_CODE != '' AND LRG.LRG_CODE = @P_LRG_CODE THEN 1 ELSE 2 END)
		     AND 1=(CASE WHEN @P_MID_CODE = '' THEN 1 WHEN @P_MID_CODE != '' AND MID.MID_CODE = @P_MID_CODE THEN 1 ELSE 2 END)
			 AND B.ITM_FORM != '3'
		   ORDER BY B.SCAN_CODE, A.INV_DT

	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	
	END CATCH
	
END

GO

