/*

-- 생성자 :	윤현빈
-- 등록일 :	2024.07.23
-- 설 명  : 시험성적서 관리 등록(BULK) LOT 생성
-- 실행문 : 

EXEC PR_STOCK_AUDIT_PUT '','','','',''

*/
CREATE PROCEDURE [dbo].[PR_TEST_REPORT_BULK_PUT]
( 
	@P_JSONDT			VARCHAR(8000) = '',
	@P_EMP_ID			NVARCHAR(20)				-- 아이디
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

	DECLARE @RETURN_CODE	INT = 0										-- 리턴코드(저장완료)
	DECLARE @RETURN_MESSAGE NVARCHAR(MAX) = DBO.GET_ERR_MSG('0')		-- 리턴메시지
	DECLARE @V_LOT_NO		NVARCHAR(30)
	
	BEGIN TRAN
	BEGIN TRY 
			
		DECLARE @TMP_ITEM TABLE (
			SCAN_CODE NVARCHAR(14),
			MODE NVARCHAR(1)
		)
		
		INSERT INTO @TMP_ITEM
		SELECT SCAN_CODE, MODE
			FROM 
				OPENJSON ( @P_JSONDT )   
					WITH (    
						SCAN_CODE NVARCHAR(14) '$.SCAN_CODE',
						MODE NVARCHAR(1) '$.MODE'
					)
				
		DECLARE CURSOR_BULK CURSOR FOR

			SELECT SCAN_CODE, MODE FROM @TMP_ITEM
			
		OPEN CURSOR_BULK

		DECLARE @P_SCAN_CODE NVARCHAR(14), 
		        @P_MODE NVARCHAR(1)

		FETCH NEXT FROM CURSOR_BULK INTO @P_SCAN_CODE, @P_MODE

			WHILE(@@FETCH_STATUS=0)
			BEGIN
				
				IF @P_MODE = 'D'
				BEGIN
					-- 오늘일자만 삭제가능, 
					DELETE FROM CD_LOT_MST WHERE PROD_DT = CONVERT(NVARCHAR, GETDATE(), 112) AND SCAN_CODE = @P_SCAN_CODE
				END

				ELSE 
				BEGIN
					--SELECT @V_LOT_NO = CONCAT(CONVERT(NVARCHAR(8), DATEADD(MONTH, EXPIRY_CNT, GETDATE()-1), 112), '-' , LOT_OIL_GB, '-', LOT_PARTNER_GB, '-', ITM_CODE) 
					--SELECT @V_LOT_NO = CONCAT(CONVERT(NVARCHAR(8), DATEADD(MONTH, EXPIRY_CNT, GETDATE()-1), 112), '-' , LOT_OIL_GB, '-UM-', ITM_CODE) 
					SELECT @V_LOT_NO = CONCAT(CONVERT(NVARCHAR(8), GETDATE(), 112), '-' , LOT_OIL_GB, '-UM-', ITM_CODE) 
						FROM CD_PRODUCT_CMN 
					   WHERE SCAN_CODE = @P_SCAN_CODE
					     AND EXPIRY_CNT IS NOT NULL AND EXPIRY_CNT != ''
						 AND LOT_OIL_GB IS NOT NULL AND LOT_OIL_GB != ''
						 --AND LOT_PARTNER_GB IS NOT NULL AND LOT_PARTNER_GB != ''
					   ;

					IF @V_LOT_NO IS NOT NULL
					BEGIN
						DECLARE @V_TMP_EXPIRY NVARCHAR(3) = ''; -- 소비기한 저장하는 곳
						DECLARE @V_EXPIRATION_DT NVARCHAR(8) = ''; -- 소비기한 저장하는 곳

						SELECT @V_TMP_EXPIRY = MGMT_ENTRY_2 FROM TBL_COMM_CD_MST WHERE CD_CL = 'LOT_PARTNER_GB' AND CD_ID = 'UM' AND MGMT_ENTRY_3 = @P_SCAN_CODE;
						IF @V_TMP_EXPIRY = '' OR @V_TMP_EXPIRY IS NULL
						BEGIN
							SELECT @V_EXPIRATION_DT = CONVERT(NVARCHAR(8), DATEADD(MONTH, EXPIRY_CNT, GETDATE()-1), 112)
								FROM CD_PRODUCT_CMN 
							   WHERE SCAN_CODE = @P_SCAN_CODE
						END
						ELSE 
						BEGIN
							SET @V_EXPIRATION_DT = CONVERT(NVARCHAR(8), DATEADD(MONTH, CAST(@V_TMP_EXPIRY AS INT), GETDATE()-1), 112);
						END
						IF NOT EXISTS (
							SELECT 1
								FROM CD_LOT_MST
							   WHERE PROD_DT = CONVERT(NVARCHAR, GETDATE(), 112)
								 AND SCAN_CODE = @P_SCAN_CODE
						)
						BEGIN
							INSERT CD_LOT_MST
							SELECT CONVERT(NVARCHAR, GETDATE(), 112)
								 , @P_SCAN_CODE
								 , @V_LOT_NO
								 , @V_EXPIRATION_DT
								 , 'K'		-- BULK
								 , ''
								 , ''
								 , 0
								 , 0
								 , 'N'
								 , NULL
								 , NULL
								 , GETDATE()
								 , @P_EMP_ID
								 , NULL
								 , NULL
						END
						ELSE
						BEGIN
							SET @RETURN_CODE = -43
							SET @RETURN_MESSAGE = DBO.GET_ERR_MSG('-43')		-- 금일 LOT가 이미 존재.
						END
					END

					ELSE
					BEGIN
						SET @RETURN_CODE = -42
						SET @RETURN_MESSAGE = DBO.GET_ERR_MSG('-42')		-- 저장실패, LOT정보누락
					END
				END
				FETCH NEXT FROM CURSOR_BULK INTO @P_SCAN_CODE, @P_MODE

			END

		CLOSE CURSOR_BULK
		DEALLOCATE CURSOR_BULK

	COMMIT;
	END TRY
	
	BEGIN CATCH	
		
		IF @@TRANCOUNT > 0
		BEGIN 
			ROLLBACK TRAN
			SET @RETURN_CODE = -1
			SET @RETURN_MESSAGE = ERROR_MESSAGE()

			--에러 로그 테이블 저장
			INSERT INTO TBL_ERROR_LOG 
			SELECT ERROR_PROCEDURE()		-- 프로시저명
				, ERROR_MESSAGE()			-- 에러메시지
				, ERROR_LINE()				-- 에러라인
				, GETDATE()	
		END 
		
	END CATCH
	SELECT @RETURN_CODE AS RETURN_CODE, @RETURN_MESSAGE AS RETURN_MESSAGE 
END

GO

