/*
-- 생성자 :	강세미
-- 등록일 :	2023.04.05
-- 수정자 : -
-- 수정일 : - 
-- 설 명  : 배차그룹삭제
-- 실행문 : 
EXEC PR_TRANS_MANAGE_GROUP_DEL 1
*/
CREATE PROCEDURE [dbo].[PR_TRANS_MANAGE_GROUP_DEL]
( 
	@P_GROUP_NO			INT = 0					-- 그룹번호
)
AS
BEGIN
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
 
	BEGIN TRY

		DECLARE @RETURN_CODE	INT = 0									-- 리턴코드
		DECLARE @RETURN_MESSAGE NVARCHAR(30) = '삭제되었습니다.'		-- 리턴메시지
		
        UPDATE PO_ORDER_HDR
            SET ORD_NO_PARENT = ORD_NO
        WHERE ORD_NO IN (SELECT A.ORD_NO FROM PO_ORDER_HDR A
				INNER JOIN PO_SCALE_GROUP B ON A.ORD_NO = B.ORD_NO
				WHERE B.GROUP_NO = @P_GROUP_NO
              )

		DELETE PO_SCALE_GROUP
        WHERE GROUP_NO = @P_GROUP_NO

        UPDATE PO_SCALE
            SET GROUP_NO = NULL
        WHERE GROUP_NO = @P_GROUP_NO


	END TRY
	
	BEGIN CATCH		
		--에러 로그 테이블 저장
		INSERT INTO TBL_ERROR_LOG 
		SELECT ERROR_PROCEDURE()	-- 프로시저명
		, ERROR_MESSAGE()			-- 에러메시지
		, ERROR_LINE()				-- 에러라인
		, GETDATE()	

		SET @RETURN_CODE = 9
		SET @RETURN_MESSAGE = '삭제 실패하였습니다.'
	END CATCH

	SELECT @RETURN_CODE AS RETURN_CODE, @RETURN_MESSAGE AS RETURN_MESSAGE, @P_GROUP_NO AS GROUP_NO
END

GO

