/*
-- 생성자 :	이동호
-- 등록일 :	2023.12.28
-- 수정자 : -
-- 수정일 : - 
-- 설 명  :  TREE 구조 정렬순서 마지막 두자리 코드값을 순번 값으로 치환해주는 함수
-- 실행문 : 
SELECT dbo.FN_DEPT_CODE_CH('0204',1)
*/
CREATE FUNCTION [dbo].[FN_DEPT_CODE_SORT_CH](
	@P_DEPT_CODE NVARCHAR(50),	
	@P_SORT_ORDER INT	
)
RETURNS VARCHAR(50)
AS 
BEGIN
	DECLARE @RETCODE NVARCHAR(50)
	DECLARE @SORT_ORDER NVARCHAR(50)
	SET @SORT_ORDER = IIF(@P_SORT_ORDER > 9, CAST(@P_SORT_ORDER AS VARCHAR), '0' + CAST(@P_SORT_ORDER AS VARCHAR))		
	SET @RETCODE = SUBSTRING(@P_DEPT_CODE, 1, LEN(@P_DEPT_CODE) - 2) + @SORT_ORDER
RETURN (	@RETCODE);
END;

GO

