
/*
-- 생성자 :	이동호
-- 등록일 :	2024.05.10
-- 수정자 : -
-- 수정일 : - 
-- 설 명  :  주문 연동 PLT 상품 정보 출력
-- 실행문 : SELECT * FROM dbo.FN_TBL_CD_PRODUCT_CMN_PLT('')
*/
CREATE FUNCTION [dbo].[FN_TBL_CD_PRODUCT_CMN_PLT]
(
	@P_ORD_NO	NVARCHAR(11) = ''	-- 주문(발주)번호
) 
RETURNS TABLE
AS

RETURN
(
	SELECT 
		ITM_CODE, SCAN_CODE, ITM_NAME, ITM_NAME_DETAIL, UNIT_CAPACITY, IPSU_QTY, PLT_BOX_QTY, UNIT_WEIGHT, PLT_MODE, QTY
	FROM (
		SELECT ITM_CODE, SCAN_CODE, ITM_NAME, ITM_NAME_DETAIL, UNIT_CAPACITY, IPSU_QTY, PLT_BOX_QTY, UNIT_WEIGHT,
			'AJ11' AS PLT_MODE, AJ11.PLT_AJ_QTY11 AS QTY
			FROM CD_PRODUCT_CMN AS A	
				INNER JOIN PO_ORDER_PLT AS AJ11 ON A.SCAN_CODE = '450004' AND AJ11.PLT_AJ_QTY11 > 0		
			WHERE AJ11.ORD_NO = @P_ORD_NO
		UNION ALL
		SELECT ITM_CODE, SCAN_CODE, ITM_NAME, ITM_NAME_DETAIL, UNIT_CAPACITY, IPSU_QTY, PLT_BOX_QTY, UNIT_WEIGHT,		
			'AJ12' AS PLT_MODE, AJ12.PLT_AJ_QTY12 AS QTY
			FROM CD_PRODUCT_CMN AS A	
				INNER JOIN PO_ORDER_PLT AS AJ12 ON A.SCAN_CODE = '450002' AND AJ12.PLT_AJ_QTY12 > 0		
			WHERE AJ12.ORD_NO = @P_ORD_NO
		UNION ALL
		SELECT ITM_CODE, SCAN_CODE, ITM_NAME, ITM_NAME_DETAIL, UNIT_CAPACITY, IPSU_QTY, PLT_BOX_QTY, UNIT_WEIGHT,		
			'NF11' AS PLT_MODE, NF11.PLT_KPP_QTY11 AS QTY
			FROM CD_PRODUCT_CMN AS A	
				INNER JOIN PO_ORDER_PLT AS NF11 ON A.SCAN_CODE = '450001' AND NF11.PLT_KPP_QTY11 > 0		
			WHERE NF11.ORD_NO = @P_ORD_NO
		UNION ALL
		SELECT ITM_CODE, SCAN_CODE, ITM_NAME, ITM_NAME_DETAIL, UNIT_CAPACITY, IPSU_QTY, PLT_BOX_QTY, UNIT_WEIGHT,	
			'NF12' AS PLT_MODE, NF12.PLT_KPP_QTY12 AS QTY
			FROM CD_PRODUCT_CMN AS A	
				INNER JOIN PO_ORDER_PLT AS NF12 ON A.SCAN_CODE = '450003' AND NF12.PLT_KPP_QTY12 > 0		
			WHERE NF12.ORD_NO = @P_ORD_NO
	) AS CMN_LOT

)

GO

