/*
-- 생성자 :	이동호
-- 등록일 :	2023.01.17
-- 수정자 : -
-- 수정일 : - 
-- 설 명  :  배송지 리스트 TREE JSON 형식 변환
-- 실행문 : SELECT dbo.FN_PARTNER_DELIVERY_TREE_JSON(0, NULL, 0, 'UM10001');
*/
CREATE FUNCTION [dbo].[FN_PARTNER_DELIVERY_TREE_JSON](
	@P_PARENTID INT,					-- 뎁스 시작점
	@P_PATH NVARCHAR(1000),		-- 뎁스 표시
	@P_DEPTH INT,						-- 뎁스 표시 시작 값
	@P_VEN_CODE NVARCHAR(7)			-- 거래처코드
)
RETURNS NVARCHAR(max)
AS BEGIN

RETURN (	

	SELECT CODE
		  , UP_CODE
		  , VEN_CODE
		  , DELIVERY_CODE
		  , DELIVERY_NAME
		  , SORT_ORDER
		  , DELIVERY_GB
		  , DELIVERY_GB_NM
		  , POST_NO
		  , ADDR
		  , ADDR_DTL
		  , ADDR + ' ' + ADDR_DTL AS FULL_ADDR
		  , CHRG_NAME
		  , TEL_NO
		  , MOBIL_NO
		  , EMAIL
		  , FAX_NO
		  , USE_YN
		  , TRANS_GB
		  , TRANS_GB_NM
		  , TRANS_SECTION
		 , _children = JSON_QUERY(dbo.FN_PARTNER_DELIVERY_TREE_JSON(T.CODE, CONCAT(@P_PATH + ',', T.CODE), @P_DEPTH + 1,@P_VEN_CODE))
	FROM (
		SELECT SUBSTRING(SUBSTRING(DELIVERY_CODE, 4, 6), 1, 2) AS CODE
			  , '' AS UP_CODE
			  , VEN_CODE
			  , DELIVERY_CODE
			  , DELIVERY_NAME
			  , A.SORT_ORDER
			  , DELIVERY_GB
			  , B.CD_NM AS DELIVERY_GB_NM
		     , POST_NO
		     , ADDR
		     , ADDR_DTL
		     , ADDR + ' ' + ADDR_DTL AS FULL_ADDR
		     , CHRG_NAME
		     , TEL_NO
		     , DBO.GET_DECRYPT(MOBIL_NO) AS MOBIL_NO
			  , EMAIL
			  , FAX_NO
		     , USE_YN
			  , C.TRANS_GB
			  , D.CD_NM AS TRANS_GB_NM
			  , C.TRANS_SECTION
		FROM CD_PARTNER_DELIVERY AS A WITH(NOLOCK)
			INNER JOIN TBL_COMM_CD_MST AS B
			     ON B.CD_CL = 'DELIVERY_GB' AND B.CD_ID = A.DELIVERY_GB
			LEFT OUTER JOIN CD_DELIVERY_PRICE AS C
				  ON A.DELIVERY_PRICE_SEQ = C.SEQ
			LEFT OUTER JOIN TBL_COMM_CD_MST AS D
				  ON D.CD_CL = 'TRANS_GB' AND D.CD_ID = C.TRANS_GB
		--WHERE SUBSTRING(DELIVERY_CODE,  LEN(DELIVERY_CODE), 1) = 1
		WHERE RIGHT(DELIVERY_CODE,  2) = '01'
		  AND VEN_CODE = @P_VEN_CODE
		UNION ALL
		SELECT SUBSTRING(DELIVERY_CODE, 4, 6) AS CODE
			  , SUBSTRING(SUBSTRING(DELIVERY_CODE, 4, 6), 1, 2) AS UP_CODE
			  , VEN_CODE
			  , DELIVERY_CODE
			  , DELIVERY_NAME
			  , A.SORT_ORDER
			  , DELIVERY_GB
			  , B.CD_NM AS DELIVERY_GB_NM
		     , POST_NO
		     , ADDR
		     , ADDR_DTL
		     , ADDR + ' ' + ADDR_DTL AS FULL_ADDR
		     , CHRG_NAME
		     , TEL_NO
		     , DBO.GET_DECRYPT(MOBIL_NO) AS MOBIL_NO
			  , EMAIL
			  , FAX_NO
		     , USE_YN
			  , C.TRANS_GB
			  , D.CD_NM AS TRANS_GB_NM
			  , C.TRANS_SECTION
		FROM CD_PARTNER_DELIVERY AS A WITH(NOLOCK)
			INNER JOIN TBL_COMM_CD_MST AS B
			     ON B.CD_CL = 'DELIVERY_GB' AND B.CD_ID = A.DELIVERY_GB
			LEFT OUTER JOIN CD_DELIVERY_PRICE AS C
				  ON A.DELIVERY_PRICE_SEQ = C.SEQ
			LEFT OUTER JOIN TBL_COMM_CD_MST AS D
				  ON D.CD_CL = 'TRANS_GB' AND D.CD_ID = C.TRANS_GB
		WHERE RIGHT(DELIVERY_CODE,  2) != '01'
		  AND VEN_CODE = @P_VEN_CODE
	) T
	WHERE EXISTS (SELECT T.UP_CODE INTERSECT SELECT @P_PARENTID) ORDER BY T.SORT_ORDER ASC
	FOR JSON PATH
)
END;

GO

