

/*
-- 생성자 :	이동호
-- 등록일 :	2024.06.20
-- 수정자 : -
-- 수정일 : - 
-- 설 명	: 주문별 입금처리 내역 > 입금번호 출력
-- 실행문 : 
*/
CREATE FUNCTION [dbo].[GET_DEPOSIT_ORD_NO](
	@P_DATE VARCHAR(8)
)
RETURNS VARCHAR(11)
AS
BEGIN
	DECLARE @DEPOSIT_NO NVARCHAR(11)	
	DECLARE @DEPOSIT_NO_CNT INT

	SELECT @DEPOSIT_NO_CNT = COUNT(MOID) + 1 FROM PA_ACCT_DEPOSIT_ORD WITH(NOLOCK) WHERE DEPOSIT_DT = @P_DATE

	IF @DEPOSIT_NO_CNT < 10
		SET @DEPOSIT_NO = @P_DATE + '00' + CAST(@DEPOSIT_NO_CNT AS VARCHAR)
	ELSE IF @DEPOSIT_NO_CNT > 9 AND @DEPOSIT_NO_CNT < 100
		SET @DEPOSIT_NO = @P_DATE + '0' + CAST(@DEPOSIT_NO_CNT AS VARCHAR)
	ELSE 
		SET @DEPOSIT_NO = @P_DATE + CAST(@DEPOSIT_NO_CNT AS VARCHAR)
	
RETURN @DEPOSIT_NO
END

GO

