






/*
-- 생성자 :	이동호
-- 등록일 :	2024.06.25
-- 설 명  : 상품의 단품 상품 재고, 박스상품의 단품 재고 
-- 수정자 :
-- 수정일 :
-- 수정내용 :

*/
CREATE VIEW [dbo].[VIEW_PRODUCT_CUR_INV_QTY] AS

	SELECT 
		CMN.SCAN_CODE,
		CMN.ITM_CODE,
		CMN.ITM_FORM,
		CMN.ITM_NAME,
		CMN.ITM_NAME_DETAIL,
		ISNULL(IIF(CMN.ITM_FORM = '2', BOX.BOX_EACH_QTY, ST1.CUR_INV_QTY), 0) AS CUR_INV_QTY		
	FROM CD_PRODUCT_CMN AS CMN WITH(NOLOCK)
		LEFT OUTER JOIN IV_PRODUCT_STAT AS ST1 WITH(NOLOCK) ON CMN.SCAN_CODE = ST1.SCAN_CODE
		LEFT OUTER JOIN (
			SELECT BX.BOX_CODE, BX.ITM_CODE, ST2.CUR_INV_QTY AS BOX_EACH_QTY 
				FROM CD_BOX_MST AS BX WITH(NOLOCK)
			INNER JOIN IV_PRODUCT_STAT AS ST2 WITH(NOLOCK) ON BX.ITM_CODE = ST2.ITM_CODE
		) AS BOX ON CMN.ITM_CODE = BOX.BOX_CODE

GO

